### ISSUE TITLE
SSL certificate verification failed

### ISSUE THREAD

**Issue by Placeto303** [PokemonGoMap/PokemonGo-Map#100]
Hello,

I've installed the PokemonGo-Map and get this with I try to start the server :

2016-08-08 11:24:50,641 [ search_worker_0][        search][    INFO] Search step 120 beginning (queue size is 151)
2016-08-08 11:24:50,641 [ search_worker_0][   auth_google][    INFO] Google User Login for: myaccount@gmail.com
2016-08-08 11:24:50,667 [ search_worker_0][        search][   ERROR] Exception in search_worker: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
Traceback (most recent call last):
  File "/root/PokemonGo-Map/pogom/search.py", line 219, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/root/PokemonGo-Map/pogom/search.py", line 266, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "/usr/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 82, in set_authentication
    self._auth_provider.user_login(username, password)
  File "/usr/lib/python2.7/site-packages/pgoapi/auth_google.py", line 55, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "/usr/lib/python2.7/site-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/usr/lib/python2.7/site-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

How can I solve this ?

Thanks !

**Comment by wschoot** [comment]
Same here, I changed my certifi to fix this:

```
### SSL errors op CentOS 6
# pip uninstall -y certifi
# pip install certifi==2015.04.28

```

**Comment by Placeto303** [comment]
I confirm it works !

Thanks wschoot !

**Comment by marcianosr** [comment]
I had the same problem. I am on windows 8.1 and can confirm that this works too!

**Comment by mikedimore** [comment]
Thanks!

**Comment by marumari** [comment]
Note that if you use certifi, requests will use it:

http://docs.python-requests.org/en/master/user/advanced/#ca-certificates

You *must* update it frequently.  Don't pin a specific version, instead use `pip install --upgrade certifi`

**Comment by wschoot** [comment]
The latest version doesn't seem to work in case of python 2.7 using SCL, that's why I downgraded manually.

**Comment by twoLegsGood** [comment]
`pip install certifi==2015.04.28` is the only thing that works for me as well
