### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by uhctuhkt** [PokemonGoMap/PokemonGo-Map#1000]
Map parse failed at 56.501040,84.992451, abandoning location. PoGoMapTomsk may be banned.
Traceback (most recent call last):
  File "/Users/sweethome/Desktop/PokemonGo Map/PokemonGo-Map/pogom/search.py", line 510, in search_worker_thread
    parsed = parse_map(args, response_dict, step_location, dbq, whq)
  File "/Users/sweethome/Desktop/PokemonGo Map/PokemonGo-Map/pogom/models.py", line 502, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by crckdns** [comment]
Banned.

**Comment by BaIthamel** [comment]
No....

People whine when i just close these things....

This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
