### ISSUE TITLE
db-cleaner overkill

### ISSUE THREAD

**Issue by Stupefy** [PokemonGoMap/PokemonGo-Map#1034]
## Expected Behavior
would expect the database to be cleaned once by one thread

## Current Behavior
database cleanup happens at almost the same time for every thread.  this causes issues with 100+ worker threads and accessing the database via a single web server.

## Possible Solution
add option to disable database cleanup for workers.

## Steps to Reproduce (for bugs)

1. run 100+ workers.. 
2. log in.. and look at the map..
3.
4.

## Context

i get the following very frequently with a web service running
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\PokemonGoMap\Build\PokemonGo-Map\pogom\app.py", line 90, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "C:\PokemonGoMap\Build\PokemonGo-Map\pogom\models.py", line 107, in get_active
    for p in query:
  File "C:\Python27\lib\site-packages\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by Stupefy** [comment]
Traceback (most recent call last):
  File "C:\PokemonGoMap\Build\PokemonGo-Map\pogom\models.py", line 575, in clean_db_loop
    query.execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 3274, in execute
    return self.database.rows_affected(self._execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked

**Comment by chuyskywalker** [comment]
Er...

```
    # db clearner; really only need one ever
    t = Thread(target=clean_db_loop, name='db-cleaner', args=(args,))
    t.daemon = True
    t.start()
```

The db cleaner is already a single thread.

**Comment by Stupefy** [comment]
within a single instance, but with 100s of workers (separate instances) you have 100s running at the same time.  using the location generator i get lots of executions of the runserver.py running all the time.  I may be wrong but i see db-cleaner running over and over and over within the same window that holds 50 or so executions of runserver.py

**Comment by cyan** [comment]
personnaly i get to many DB cleaner with just 2 worker,  (just started a new scan with a mysql DB (lot of data inside but not the whole USA) and had to wait like 5-10minutes for the scan to start :/)

**Comment by chuyskywalker** [comment]
Well, see, you're confusing things now. You're running multiple processes, each has a db cleaning thread. The instances have little to no idea the others exist, thus can't know that one vs the other shouldn't run a cleaning thread. It's also worth pointing out that this behavior is now new, there's a just a log line for it now. (In fact, the threaded version, which is fairly new, actually runs _less_ frequently than the previous version which ran with every db update!)

If you'd like to add a PR to be able to toggle the db clean up, I'd be happy to review that.

**Comment by rrbailey89** [comment]
@chuyskywalker how does run run all workers threaded in one window?

**Comment by gabrielsoldani** [comment]
+1 for a database cleanup toggle. It makes almost no difference in practice but makes sense.

**Comment by averylarry** [comment]
Is this the same as #916?

**Comment by BaIthamel** [comment]
yeah I +1 a db cleaner toggle :P i'll close #916 as a dupe since the toggle is only mentioned here

**Comment by shadi1989** [comment]
Isnt it possible that you need to do the db-cleanup manually via --db-cleanup or -dbc for the first worker and the runserver.py shows an error if there isnt one specified...

**Comment by Stupefy** [comment]
i still get errors consistently with web server thread

2016-08-31 18:14:11,319 [      db-cleaner][        models][   ERROR] Exception in clean_db_loop: database is locked
Traceback (most recent call last):
  File "C:\PokemonGoMap\Build\PokemonGo-Map\pogom\models.py", line 818, in clean_db_loop
    query.execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 3274, in execute
    return self.database.rows_affected(self._execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked

**Comment by pyr0ball** [comment]
@Stupefy you're posting in the wrong place, but jsut FYI your issue would be solved by switching to MySQL

**Comment by jnovack** [comment]
The follow cases may exist:

* 1 instance running both scan and web (private home use).
* X number of scan instances (covering multiple areas) + 1 web instance (single serving site).
* X number of scan instances (covering multiple areas) + x web instances (load balanced).

I think the only fair solution is a `--db-cleanup X` tag where `X` is the number of minutes to clean up (For those people scanning large areas, they might want longer times).

**Comment by averylarry** [comment]
My first thought was to only have the db cleanup thread on web instances.  Maybe that's a decent compromise that doesn't kill any puppies?
My second thought is probably overkill -- but I thought about having a database maintenance process that could be enabled or disabled per instance, very much like the webserver can be enabled or disabled (-os, -ns).  That way you can make sure you only have 1 instance that is doing the database maintenance tasks (and maybe more db maint. tasks will be found).

**Comment by JaymerJaymer** [comment]
i run multiple python instances (multiple terminal windows on OS X).
Only 1 is a server, the others have the -ns flag, or else there is an error. 
Why not have only that one clean?

**Comment by justsomedudeonthenet** [comment]
@JaymerJaymer some people run quite a few instances with server enabled - think personal hex scanners for you and 50 of your closest friends.

So a parameter to turn it off would be ideal.
