### ISSUE TITLE
Undefined error. Program blocked

### ISSUE THREAD

**Issue by danieleserra** [PokemonGoMap/PokemonGo-Map#1041]
## Current Behavior
I run the program with the command line:
python runserver.py -a ptc -u he**a -p *** -l "***" -st 11 -k AIzaSy***PtCQ -sd 2 --spawnpoints-only -ng -nk -ld 1 -lr 4000 -mf 5000

after 10 minutes a receive this block:

2016-08-28 21:07:31,907 [ search-worker-0][        search][    INFO] Searching a
t 39.150388,9.513832
2016-08-28 21:07:32,276 [ search-worker-0][        models][    INFO] Parsing fou
nd 0 pokemons, 0 pokestops, and 0 gyms
[2016-08-28 21:07:33,099] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch
_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch
_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_requ
est
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Dani\Desktop\PokemonGo-Map\pogom\app.py", line 90, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "C:\Users\Dani\Desktop\PokemonGo-Map\pogom\models.py", line 107, in get_a
ctive
    for p in query:
  File "C:\Python27\lib\site-packages\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2016-08-28 21:07:33,099 [      Thread-177][           app][   ERROR] Exception o
n /raw_data [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch
_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch
_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_requ
est
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Dani\Desktop\PokemonGo-Map\pogom\app.py", line 90, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "C:\Users\Dani\Desktop\PokemonGo-Map\pogom\models.py", line 107, in get_a
ctive
    for p in query:
  File "C:\Python27\lib\site-packages\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
Exception in thread search-overseer:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Dani\Desktop\PokemonGo-Map\pogom\search.py", line 278, in searc
h_overseer_thread
    locations = get_hex_location_list(args, current_location)
  File "C:\Users\Dani\Desktop\PokemonGo-Map\pogom\search.py", line 319, in get_h
ex_location_list
    spawnpoints = set((d['latitude'], d['longitude']) for d in Pokemon.get_spawn
points(s, w, n, e))
  File "C:\Users\Dani\Desktop\PokemonGo-Map\pogom\models.py", line 238, in get_s
pawnpoints
    return list(query.dicts())
  File "C:\Python27\lib\site-packages\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked

2016-08-28 21:08:18,232 [      db-cleaner][        models][    INFO] Regular dat
abase cleaning complete
2016-08-28 21:09:18,233 [      db-cleaner][        models][    INFO] Regular dat
abase cleaning complete

And now it blocked. I have to restart the command. It works very well everyday, but sometimes there is this "database blocked"

## Steps to Reproduce (for bugs)
I don't know. Maybe random

## Your Environment
* Version used:
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 7

**Comment by danieleserra** [comment]
I forgot to extecute:

npm install
npm run build

after the pulls from git. Maybe this explainds the problem. Im sorry for the thread.
