### ISSUE TITLE
Webpage not loading/Stacktrace

### ISSUE THREAD

**Issue by KyleBoyer** [PokemonGoMap/PokemonGo-Map#1065]
I get nothing when I visit the localhost:5000 url, and on my console - I have:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
TypeError: wrap_socket() got an unexpected keyword argument 'error_log'
<Greenlet at 0x10cd33910: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x10cc5a790 fileno=9 address=127.0.0.1:5000>>(<socket at 0x10ce9d350 fileno=32 sock=127.0.0.1:50, ('127.0.0.1', 49343))> failed with TypeError

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
TypeError: wrap_socket() got an unexpected keyword argument 'error_log'
<Greenlet at 0x10cd33910: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x10cc5a790 fileno=9 address=127.0.0.1:5000>>(<socket at 0x10ce9d350 fileno=32 sock=127.0.0.1:50, ('127.0.0.1', 49345))> failed with TypeError

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
