### ISSUE TITLE
Loading slow since gevent

### ISSUE THREAD

**Issue by shadi1989** [PokemonGoMap/PokemonGo-Map#1082]
## Expected Behavior
Expected to run at same speed or faster compared to flask :)

## Current Behavior
Running gevent slows the loading of the web-based part. Can take up to 30-seconds before its fully loaded. Disabling the pokemons/stops/etc doesn't make any difference.

## Possible Solution
go back to flask or fix the issue with gevent(preferred solution)

## Steps to Reproduce (for bugs)
Scripted a batch file who starts 5 instances with 80 accounts total. Nothing special, ran perfectly with a build before gevent.

## Context
As thunderfox said in the Discord, using gevent should be faster with more workers then flask was. that isn't the outcome with me and a few others in discord.

Running iPokeGo iPhone app is faster then before(doesn't use gevent)

## Your Environment
* Version used: Maps build 1064
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10, fast-ring. 16GB ram

FYI: never filled an issue so ask questions and i'll try to answer :)

**Comment by c133** [comment]
I noticed the same behavior. I am using ~40 accounts to spawnscan a 4km radius area. 

After pulling the gevent commit, I noticed the map loads a lot slower than before when using flask. 

I would also get errors every now and then:

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
  File "/root/PokemonGo-Map/pogom/app.py", line 75, in fullmap
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 851, in get_or_select_template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 812, in get_template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 774, in _load_template
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 57, in get_source
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 82, in _get_source_fast
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 171, in get_source
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 151, in open_if_exists
IOError: [Errno 24] Too many open files: '/root/PokemonGo-Map/templates/map.html'`

I am back to running flask for now.

**Comment by brettgus** [comment]
I'm having the same issue after upating to the gevent commit

**Comment by c133** [comment]
Also for the above error, "too many open files", do I just need to increase the open files ulimit on my server? Or do I need to use something like haproxy?

**Comment by cbogithub** [comment]
@c133  have you share any help about use PokemonGo-Map with haproxy ?

**Comment by c133** [comment]
Nope, I am looking for help as well on how to use it

**Comment by aldarund** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1084
The problem is because u cant use gevent with blocking operations. Or u doomed.

**Comment by ro4sho** [comment]
I can second this. I don;t know if it is only Gevent. Since updating to the latest version on my Raspberry Pi the web app will load only the first time and then hangs after a short while (10 seconds). The script seems to work fine as I can see the output on the command line. 
But the web app is simply inaccessible.

**Comment by aldarund** [comment]
@ro4sho yes its  a gevent problem. rollback to pregevent commit

**Comment by ro4sho** [comment]
@aldarund Thank you Aldarund. Do you happen to know the commit ID? Or how I can find it? I'm a little lost.

**Comment by aldarund** [comment]
@ro4sho 9a1ef2582275f142a986933716a054be8adcf25c

**Comment by shadi1989** [comment]
Does really no-one has a fix for this? multiple ppl are having this issue on discord.

**Comment by aldarund** [comment]
@shadi1989 read my comments here -> https://github.com/PokemonGoMap/PokemonGo-Map/pull/1084

**Comment by jchristi** [comment]
As @aldarund said in #1084, the real solution should be to replace gevent with something like gunicorn.

**Comment by FrostTheFox** [comment]
gevent has been reverted to flask for the time being, a different solution may be coming in the future.
