### ISSUE TITLE
Can't install (fixed)

### ISSUE THREAD

**Issue by tr1p0z** [PokemonGoMap/PokemonGo-Map#1117]
C:\Users\isaac\Desktop\map\PokemonGo-Map>runserver.py
Traceback (most recent call last):
  File "C:\Users\isaac\Desktop\map\PokemonGo-Map\runserver.py", line 20, in <module>
    from gevent import pywsgi
  File "C:\Python27\lib\site-packages\gevent\__init__.py", line 49, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 11, in <module>
    from greenlet import greenlet, getcurrent, GreenletExit
ImportError: DLL load failed: No se encontr¾ el proceso especificado.

**Comment by tr1p0z** [comment]
Fixed updating from 2.7 to 2.7.12 (python)
