### ISSUE TITLE
Error starting runserver.py

### ISSUE THREAD

**Issue by rpc** [PokemonGoMap/PokemonGo-Map#124]
when try to run the server (`python runserver.py -a ptc ...`) on OS X El Capitan

```
Traceback (most recent call last):
  File "runserver.py", line 29, in <module>
    import pgoapi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/rpc_api.py", line 50, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/usr/local/lib/python2.7/site-packages/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 16, in <module>
    from POGOProtos.Networking import Requests_pb2 as POGOProtos_dot_Networking_dot_Requests__pb2
  File "/usr/local/lib/python2.7/site-packages/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py", line 23, in <module>
    ENCOUNTER\x10\x91\x01\x12!\n\x1c\x43OLLECT_DAILY_DEFENDER_BONUS\x10\x92\x01\x12\x14\n\x0fUPGRADE_POKEMON\x10\x93\x01\x12\x19\n\x14SET_FAVORITE_POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by LIJE** [comment]
whats ur complete input?

**Comment by tBuLi** [comment]
I have the exact same error, using the line from the docs:
```
python runserver.py -a ptc -u johndoe -p ilovemama -l "400 Broad St, Seattle, WA 98109, USA" -st 5
```

**Comment by rpc** [comment]
@LIJE that is the complete output ..

**Comment by WhizzardBlizzard** [comment]
did you install the reqs?
> pip install -r requirements.txt

**Comment by rpc** [comment]
@WhizzardBlizzard yes both like that and with `--upgrade` (just in case)

**Comment by kauegimenes** [comment]
Same problem! (OS X)
Python 2.7.12

**Comment by iaudrey** [comment]
same

**Comment by tBuLi** [comment]
This was already solved apparently:
https://github.com/PokemonGoMap/PokemonGo-Map/issues/92

Following the steps there solved it for me

**Comment by iaudrey** [comment]
i uninstalled and reinstalled requirements. still with the error

**Comment by tBuLi** [comment]
Did you also nuke your previous install using 
``pip uninstall -r requirements.txt``

After that, make sure it's really gone from brew, if not run ``brew uninstall`` again. Then reinstall using
``
pip install --upgrade -r requirements.txt
``

(I didn't want to advise the mass uninstall since it might break some of your other projects if you still need then and are not working in a virtualenv)

**Comment by rpc** [comment]
@tBuLi removing protobuf and uninstall requirements.txt then installing it, solved the problem. Its now running. Thanks !

**Comment by badubiduba** [comment]
Even unistalling and reinstalling everything I still get the same error:

```
Traceback (most recent call last):
  File "runserver.py", line 29, in <module>
    import pgoapi
  File "C:\Python27\lib\site-packages\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 36, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "C:\Python27\lib\site-packages\pgoapi\auth_google.py", line 33, in <modul
e>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>

    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in
<module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <modu
le>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <modu
le>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, i
n <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46,
in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in
 load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'


```

**Comment by iaudrey** [comment]
Here's how I got it to work:
`brew uninstall protobuf`
`pip uninstall -r requirements.txt`
`pip install --upgrade -r requirements.txt`
`brew install node`
`npm install`

**Comment by harshiscoolguy** [comment]
I got it to work by using the following command.

sudo -H pip install --upgrade --ignore-installed -r requirements.txt

**Comment by BaIthamel** [comment]
Looks like this is a support issue. You know the drill.

**Comment by grillbude** [comment]
I'm all have applied steps, but still does not work : ( ...

worked according to these instructions ...
