### ISSUE TITLE
Multiple Account Scanning using Batch Script Calls

### ISSUE THREAD

**Issue by Crazy-Clown** [PokemonGoMap/PokemonGo-Map#134]
So I have a system I created with a batch script that calls several other scripts and launches the following command:

```
C:\Python27\Python.exe runserver.py -l "LOCATION" -st 7 -ns -a ptc -u USER -p PASS
```

Note the -ns meaning it does not run the web server (or at least didnt with the original project from AHAAAAAAAA.  I have attempted to launch a few of my account scripts but am getting the following error:

```
2016-08-08 08:07:24,855 [      MainThread][     runserver][    INFO] Parsed loca
tion is: 44.0985/-79.5940/0.0000 (lat/lng/alt)
2016-08-08 08:07:24,855 [      MainThread][     runserver][    INFO] Parsing of
Pokestops disabled
2016-08-08 08:07:24,855 [      MainThread][     runserver][    INFO] Parsing of
Gyms disabled
2016-08-08 08:07:24,871 [      MainThread][        models][    INFO] Connecting
to local SQLite database
2016-08-08 08:07:24,871 [   search_thread][        search][    INFO] Search over
seer starting
2016-08-08 08:07:24,871 [   search_thread][        search][    INFO] Starting se
arch worker threads
2016-08-08 08:07:24,871 [   search_thread][        search][    INFO] New locatio
n caught, moving search grid
2016-08-08 08:07:24,871 [ search_worker_0][        search][    INFO] Search step
 1 beginning (queue size is 0)
2016-08-08 08:07:24,871 [ search_worker_0][      auth_ptc][    INFO] PTC User Lo
gin for: <USER HERE>
2016-08-08 08:07:26,634 [ search_worker_0][      auth_ptc][   ERROR] Could not r
etrieve token: Your username or password is incorrect. You have 3 attempts left
before you will be locked out of your account for 15 minutes.
2016-08-08 08:07:26,665 [ search_worker_0][        search][   ERROR] Exception i
n search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-develop\pogom\search.py", l
ine 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-develop\pogom\models.py", l
ine 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'
2016-08-08 08:07:26,680 [ search_worker_0][        search][    INFO] Search step
 2 beginning (queue size is 125)
2016-08-08 08:07:26,680 [ search_worker_0][      auth_ptc][    INFO] PTC User Lo
gin for: <USER HERE>
2016-08-08 08:07:27,164 [ search_worker_0][      auth_ptc][   ERROR] Could not r
etrieve token: Your username or password is incorrect. You have 2 attempts left
before you will be locked out of your account for 15 minutes.
2016-08-08 08:07:27,211 [ search_worker_0][        search][   ERROR] Exception i
n search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-develop\pogom\search.py", l
ine 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-develop\pogom\models.py", l
ine 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'
2016-08-08 08:07:27,211 [ search_worker_0][        search][    INFO] Search step
 3 beginning (queue size is 124)
2016-08-08 08:07:27,226 [ search_worker_0][      auth_ptc][    INFO] PTC User Lo
gin for: <USER HERE>
2016-08-08 08:07:27,680 [ search_worker_0][      auth_ptc][   ERROR] Could not r
etrieve token: Your username or password is incorrect. You have 1 attempts left
before you will be locked out of your account for 15 minutes.
2016-08-08 08:07:27,710 [ search_worker_0][        search][   ERROR] Exception i
n search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-develop\pogom\search.py", l
ine 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-develop\pogom\models.py", l
ine 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'
2016-08-08 08:07:27,726 [ search_worker_0][        search][    INFO] Search step
 4 beginning (queue size is 123)
2016-08-08 08:07:27,726 [ search_worker_0][      auth_ptc][    INFO] PTC User Lo
gin for: <USER HERE>
Traceback (most recent call last):
  File "runserver.py", line 163, in <module>
    time.sleep(60)
```

And it goes on and on.  Note I did replace the text USER HERE to protect my account identity.  I tried to log into the PTC through the website and my account is locked for 15 minutes because the script kept looping and it locked my account out.

What is the best way for me to continue to use multiple accounts as I have a system that maps my whole town (not in a perfect beehive) but in a perfect overlapping instance of the map scan locations.

Any help would be greatly appreciated.

Thanks.

**Comment by molecul** [comment]
Yes, I have the same problem. Attached the part of error and some debug information:

```
2016-08-08 16:20:41,707 [      MainThread][     runserver][    INFO] Parsed location is: 51.5448/46.0095/0.0000 (lat/lng/alt)
2016-08-08 16:20:41,712 [      MainThread][        models][    INFO] Connecting to MySQL database on 127.0.0.1:3306
2016-08-08 16:20:41,719 [   search_thread][        search][    INFO] Search overseer starting
2016-08-08 16:20:41,719 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-08 16:20:41,719 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-08 16:20:41,720 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 26)
2016-08-08 16:20:41,722 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: sarbsmb01
2016-08-08 16:20:42,829 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-08 16:20:42,830 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-08 16:20:43,091 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.

> {'auth_ticket': {'end': 'au1K16Dit2RD758gkjOGNw==',
>                  'expire_timestamp_ms': 1470664246738L,
>                  'start': 'I4qbxJNm1YQ1IyLwontICe0+ek1b/RbZphxYGQGzqbYBhDuR2DwYbqnasvJinmaNAGViOzZqYGQM/zO2SZaF6p3hiVoAmrRmHdAznkIRzPw='},
>  'request_id': 525043123568722753L,
>  'responses': {'GET_MAP_OBJECTS': {}},
>  'status_code': 3}
> 

2016-08-08 16:20:43,713 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds
Traceback (most recent call last):
  File "/home/user/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/home/user/PokemonGo-Map/pogom/models.py", line 301, in parse_map
    cells = cells['map_cells']
KeyError: 'map_cells'

```

**Comment by DJWassink** [comment]
Having the same issue on windows. Note that running a single line out of the bat script results in a correct login while running it through the bat script results in a failed login. 
The username and password are correct since logging in on the PTC site works.

**Comment by Crazy-Clown** [comment]
> as we can see, key GET_MAP_OBJECTS have a empty dictionary value (should be contains map_cells).

Is there any way to temporarily fix this?

**Comment by Kasmodan1** [comment]
You Need to login and actually play though the first 10 sec of game play and select your first pokemon. Then the scanner will work for your PTC login. This is what I did to get my new accounts to work.

**Comment by Infernoman** [comment]
accept the terms of service in game then the accounts will work https://github.com/Infernoman/PoGoTos

**Comment by Crazy-Clown** [comment]
Some of my PTC accounts are not working - had to make them Google Accounts.  Accepted TOS and they are working now.  I made the mistake of making the passwords larger than 15 characters long, and the iOS client doesn't like the PTC passwords to be that long, and fails to login.  Works on the web, but then throws an error trying to reset password as it states it's incorrect.  *sigh*.

But anyhow, all is good now - with Google Accounts and accepting ToS as you guys had mentioned.  Thank you.

**Comment by Infernoman** [comment]
Please close your issue when possible :) glad to be of help.
