### ISSUE TITLE
Broken Pipe Error 32 Flask

### ISSUE THREAD

**Issue by Demokdawa** [PokemonGoMap/PokemonGo-Map#1426]
Since i re-launched my map few days ago, i get these errors 👍 

Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.target(self.args, *self.kwargs)
File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
self.handle_error(request, client_address)
File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
self.finish_request(request, client_address)
File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python2.7/SocketServer.py", line 654, in init
self.finish()
File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
self.wfile.close()
File "/usr/lib/python2.7/socket.py", line 283, in close
self.flush()
File "/usr/lib/python2.7/socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

But I know this has been already reported. My problem is that i get this error every second. So every error slow my server a bit, and after 10 minutes, the server is so slow that he can't continue to scan and my ss scan is like 600 secs behind....

I only have 30 clients connected, not that much. I'm on linux.

It's possible to go to gevent again ?

Thx

**Comment by BaIthamel** [comment]
You know this is a duplicate.

**Comment by Demokdawa** [comment]
Yeah, but no one seems to care about this....

This issue is here for month without any comment or answer..
