### ISSUE TITLE
KeyError on 'last_modified': calendar.timegm(pokestops[f['id']]['last_modified'].timetuple())

### ISSUE THREAD

**Issue by Cartman123** [PokemonGoMap/PokemonGo-Map#1449]
## Expected Behavior

It should scan pokestops without errors while running webhooks.
## Current Behavior

An error is thrown if scannin pokestops:
```
[ search-worker-0][        search][   ERROR] Map parse failed at XXXXXXX,XXXXXX, abandoning location. ACCOUNT may be banned.
Traceback (most recent call last):
  File "PokemonGo-Map/pogom/search.py", line 510, in search_worker_thread
    parsed = parse_map(args, response_dict, step_location, dbq, whq, api)
  File "PokemonGo-Map/pogom/models.py", line 883, in parse_map
    'last_modified': calendar.timegm(pokestops[f['id']]['last_modified'].timetuple()),
KeyError: u'5dc9b3d5ba49483499fd2bc94093f07f.16'
```
## Possible Solution

I'm running -nk (no pokestops) as a workaround.
## Steps to Reproduce (for bugs)

1. Pull latest develop
2. Run map without -nk and with -wh (webhook)

## Context

The last_modified column is present on the database. I've also tried clearing it with no success.
## Your Environment

* Version used: Latest commit 2b8815237cf250ccb9f4c60b44cd9979559e888a
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu 14.04

**Comment by Cartman123** [comment]
This is a duplicate of #1448. I was writing this one at the same time, it seems, so I'm closing it.
