### ISSUE TITLE
mysql database wasn't updated on update~

### ISSUE THREAD

**Issue by crckdns** [PokemonGoMap/PokemonGo-Map#1462]
Hey there,
I've decided to update from commit b52ba3b7b699d33f51564998d3cb7c5e4db75353 to the latest one..
pulled the git, started web instance, it started to update sql db from v7 to v9 ..but "hung" there for long time, so I killed it~  now it seems the DB isn't updated and so no run is possible anymore.
any manual solution for that?

## Expected Behavior
it starts without errors

## Current Behavior
the webserver doesn't start with following error:
` $ ./web.sh
2016-10-04 22:27:53,604 [      MainThread][     runserver][    INFO] Parsed location is: xxx/yyy/zzz (lat/lng/alt)
2016-10-04 22:27:53,604 [      MainThread][     runserver][    INFO] Parsing of Pokestops disabled
2016-10-04 22:27:53,610 [      MainThread][        models][    INFO] Connecting to MySQL database on localhost:3306
[2016-10-04 22:27:54,739] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/clients/client1/web1/virtual/servers/pogo/pogodev/pogom/app.py", line 164, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "/var/www/clients/client1/web1/virtual/servers/pogo/pogodev/pogom/models.py", line 140, in get_active
    for p in query:
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1054, u"Unknown column 't1.last_modified' in 'field list'")
`

## Possible Solution
?

## Steps to Reproduce (for bugs)

1. git pull, pip install -r requirements, npm install
2. start webserver
3. "updating database from 7 to 9" -> waiting for 3 minutes -> ctrl+c
4. start webserver -> errors

## Context
no funcion anymore

## Your Environment

* Version used: commit df13b8e6c0f238f94608d067fadeaca7d42dc958 (latest)
* Environment name and version (e.g. Python 2.7): py 2.7
* Operating System and version (desktop or mobile): debian

**Comment by Climbgunks** [comment]
depends on what you mean by recover.. if you just want to get it running again, then just drop the db completely 

mysql -p     # if you set a password
drop database  pokemongomapdb;

and recreate it as you did the first time...see the steps in https://pgm.readthedocs.io/en/develop/extras/mysql.html

**Comment by crckdns** [comment]
Solved already, sorry for the panic :D
 
`
UPDATE `c1pogo1`.`versions`
SET
`val` = 7
;
`
and then removed all changes which were already made by
`ALTER table c1pogo1.pokemon drop individual_attack, drop individual_defense, drop individual_stamina, drop move_1, drop move_2;`

I had just to wait longer for it to migrate from 7 to 9 ...database has over 800k entries~

Case solved ^^
