### ISSUE TITLE
Issue connecting to mySQL database ('Too many connections')

### ISSUE THREAD

**Issue by Schwaitz** [PokemonGoMap/PokemonGo-Map#1533]
So I have a large local machine running the back end searchers (no webserver), and then sending the data up into a mySQL database on a AWS cloud server. From the same server, I am running just the front end webserver, which gets it's data from the mySQL database that is local.

The searchers are running fine, but when I attempt to run the webserver, I recieve this error:

2016-11-13_ 00:22:33,552 [      MainThread][        models][    INFO] Connecting to MySQL database on localhost:3306
2016-11-13 00:22:33,553 [      MainThread][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "/home/ubuntu/GOMap/runserver.py", line 293, in <module>
    main()
  File "/home/ubuntu/GOMap/runserver.py", line 196, in main
    create_tables(db)
  File "/home/ubuntu/GOMap/pogom/models.py", line 1170, in create_tables
    db.connect()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/pool.py", line 128, in _connect
    conn = super(PooledDatabase, self)._connect(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3929, in _connect
    return mysql.connect(db=database, **conn_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 690, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 907, in connect
    self._get_server_information()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1209, in _get_server_information
    packet = self._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
OperationalError: (1040, u'Too many connections')

Thoughts? I am inserting into the mySQL database an awful lot from my local machine, but it has worked in the past.

**Comment by FrostTheFox** [comment]
You need to up your MySQL server max connections.

**Comment by Schwaitz** [comment]
@FrostTheFox There is no limit to the connections. I started the webserver while the other one wasn't running, and realized that I had it set to purge the database on before running. It is working now.

**Comment by FrostTheFox** [comment]
There's obviously a limit, that's why you are getting that error. The error doesn't just appear out of thin air.

**Comment by Thyllz** [comment]
I had the same problem.
Just open MySQL Client(MariaDB xx.x(x64))
Enter password (or just hit Enter if no password has been set)

Run:
**show variables like "max_connections";**
(this shows the current limit)

Run:
**set global max_connections = 200;**
(where 200 = whatever # you want to increase the limit to)

Hope this helps.
