### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-gbilpg_j/wsgiref/

### ISSUE THREAD

**Issue by baskettcase** [PokemonGoMap/PokemonGo-Map#1555]
Im on OS X and am using Python 2.7.12 and pip 9.0.1 when I ran

`sudo -H pip install -r requirements.txt`

I got the following error:

`Collecting wsgiref==0.1.2 (from -r requirements.txt (line 10))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-gbilpg_j/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/tmp/pip-build-gbilpg_j/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-gbilpg_j/wsgiref/`

Any ideas?

**Comment by baskettcase** [comment]
Ok I might have figured this one out.. even though Im using Python 2.7.12, when I see the pip version it says it is a lib of Python 3.5 so I need to figure out how to use the right version of Python with pip.

**Comment by baskettcase** [comment]
Ok apparently pip was trying to use my Python 3.5 install instead of 2.7 so I replace pip with pip2.7 and that worked. Closing the issue now.
