### ISSUE TITLE
Can't run runserver.py, it seems that can't get sqlite3 version

### ISSUE THREAD

**Issue by tristaoeast** [PokemonGoMap/PokemonGo-Map#165]
When I try to run the runserver.py I get the following error
```
Traceback (most recent call last):
  File "./runserver.py", line 45, in <module>
    from pogom.app import Pogom
  File "/home/tmic/PokemonGo-Map-2.2.0/pogom/app.py", line 17, in <module>
    from .models import Pokemon, Gym, Pokestop, ScannedLocation
  File "/home/tmic/PokemonGo-Map-2.2.0/pogom/models.py", line 10, in <module>
    from playhouse.flask_utils import FlaskDB
  File "/home/tmic/.pyenv/versions/2.7.10/lib/python2.7/site-packages/playhouse/flask_utils.py", line 12, in <module>
    from playhouse.db_url import connect as db_url_connect
  File "/home/tmic/.pyenv/versions/2.7.10/lib/python2.7/site-packages/playhouse/db_url.py", line 7, in <module>
    from playhouse.pool import PooledMySQLDatabase
  File "/home/tmic/.pyenv/versions/2.7.10/lib/python2.7/site-packages/playhouse/pool.py", line 218, in <module>
    from playhouse.sqlite_ext import SqliteExtDatabase
  File "/home/tmic/.pyenv/versions/2.7.10/lib/python2.7/site-packages/playhouse/sqlite_ext.py", line 74, in <module>
    FTS_VER = sqlite3.sqlite_version_info[:3] >= (3, 7, 4) and 'FTS4' or 'FTS3'
AttributeError: 'NoneType' object has no attribute 'sqlite_version_info'
```

## Expected Behavior

It should start the map

## Your Environment
* Version: V2.2.0 Stable with api fix
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile): Ubuntu 14.04

**Comment by chuyskywalker** [comment]
Based on some googling, this looks like you're missing the sqlite library for some reason. For example: https://github.com/theotherp/nzbhydra/issues/158

Since this is very likely a problem with your environment and not PokemonGo-Map itself, I'm going to close this issue. If it turns out to be a problem with this application, we can reopen.

**Comment by tristaoeast** [comment]
I have  python2.7.10, bot sure if it's related, but how can I upgrade to 2.7.12? I'm on ubuntu 14.04

**Comment by tallakt** [comment]
These commands fixed the issue for me. Not sure qhy, as they all reported that no changes had been made to my system:


```
  $ pip install sqlite3
  $ sudo pip install pysqlite
  $ sudo -H pip install pysqlite
  $ sudo -H pip install --upgrade pysqlite
```
