### ISSUE TITLE
Centos 6.8 Exception - Invalid Syntax

### ISSUE THREAD

**Issue by shivampaw** [PokemonGoMap/PokemonGo-Map#170]
After grunt build, pip install etc and setting up when I run the app I get the following error:

```
Traceback (most recent call last):
  File "runserver.py", line 29, in <module>
    import pgoapi
  File "/usr/lib/python2.6/site-packages/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/lib/python2.6/site-packages/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/usr/lib/python2.6/site-packages/pgoapi/rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/usr/lib/python2.6/site-packages/pgoapi/utilities.py", line 38, in <module>
    from geopy.geocoders import GoogleV3
  File "/usr/lib/python2.6/site-packages/geopy/__init__.py", line 11, in <module>
    from geopy.point import Point
  File "/usr/lib/python2.6/site-packages/geopy/point.py", line 9, in <module>
    from geopy.format import (
  File "/usr/lib/python2.6/site-packages/geopy/format.py", line 119
    for n, d
      ^
SyntaxError: invalid syntax
```

**Comment by DeviantEng** [comment]
This project requires Python 2.7+.  CentOS 6.x defaults with Python 2.6.  You need to install Python 2.7, or use a different distro.

**Comment by chuyskywalker** [comment]
^

**Comment by AcidicSkittles** [comment]
@shivampaw 
Centos 6 needs python 2.7 because it ships with 2.6, you have to install it along side python 2.6. Here's what I did: (you can probably install from an rpm somewhere if you don't want to do from source)
```
yum groupinstall "Development tools"
yum install zlib-devel
yum install bzip2-devel
yum install openssl-devel
yum install ncurses-devel
yum install sqlite-devel

cd /opt
wget --no-check-certificate https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz
tar xf Python-2.7.6.tar.xz
cd Python-2.7.6
./configure --prefix=/usr/local
make && make altinstall
```
Then to get pip
```
/usr/local/bin/python2.7 -m ensurepip
```
then you can use it like python2.7 -m pip install …

This won't be the first headache you encounter. Centos 6 also ships with glibc 2.12 and we need glibc 2.14.
```
mkdir ~/glibc_install; cd ~/glibc_install 
wget http://ftp.gnu.org/gnu/glibc/glibc-2.14.tar.gz
tar zxvf glibc-2.14.tar.gz
cd glibc-2.14
mkdir build
cd build
../configure --prefix=/opt/glibc-2.14 && make -j4 && make install
```
Then to run the map you have to do
```
LD_PRELOAD='/opt/glibc-2.14/lib/libc-2.14.so' python2.7 runserver.py ...etc
```
