### ISSUE TITLE
Unexpected token ILLEGAL when running npm run build

### ISSUE THREAD

**Issue by HardTacos** [PokemonGoMap/PokemonGo-Map#175]
When running `npm run build` or `grunt build` I am receiving the following issue:

````
$ npm run build

> pogomap@0.1.0 build C:\Users\eleme\Desktop\PokemonGo-Map-develop
> grunt build

C:\Users\eleme\Desktop\PokemonGo-Map-develop\node_modules\grunt\node_modules\grunt-legacy-log\node_modules\lodash\dist\lodash.js:4788
    /**
    ^^^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\eleme\Desktop\PokemonGo-Map-develop\node_modules\grunt\node_modules\grunt-legacy-log\index.js:20:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! pogomap@0.1.0 build: `grunt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pogomap@0.1.0 build script 'grunt build'.
npm ERR! This is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\eleme\Desktop\PokemonGo-Map-develop\npm-debug.log
````

Anyone know what this error is and how to fix it?

**Comment by numb401** [comment]
Upgrade to node v6 and re-run the npm and grunt commands

**Comment by BaIthamel** [comment]
For support please ask in discord.
