### ISSUE TITLE
String indices error

### ISSUE THREAD

**Issue by DMHKE** [PokemonGoMap/PokemonGo-Map#176]
Hello, i installed all correctly(as far as i know), im using windows 10 and Python 2.7.10 and when i launch the map i get the following log and the map in my browser just shows that an error has occurred.

2016-08-08 18:29:55,443 [ search_worker_0][   auth_google][    INFO] Google User Login successful.
2016-08-08 18:29:55,446 [ search_worker_0][   auth_google][    INFO] Request Google Access Token...
2016-08-08 18:29:55,612 [ search_worker_0][   auth_google][    INFO] Google Access Token successfully received.
2016-08-08 18:29:56,321 [ search_worker_0][        search][   ERROR] Exception in search_worker: string indices must be integers, not str
Traceback (most recent call last):
  File "C:\Users\test1\Downloads\PokemonGo-Map-develop\PokemonGo-Map-develop\pogom\search.py", line 242, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "C:\Users\test1\Downloads\PokemonGo-Map-develop\PokemonGo-Map-develop\pogom\models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: string indices must be integers, not str

How can i fix it?

**Comment by timlinde** [comment]
This seems to happen when you have not accepted ToS on your PTC account.

**Comment by DMHKE** [comment]
Well, but this is a google account not PTC.

**Comment by Frozen-byte** [comment]
we may include automatic TOS accept routine into the code, to minimize such Issues.

**Comment by Crazy-Clown** [comment]
Yea, unfortunately I had to change my PTC accounts to Google Accounts because they were always getting locked out - and I had passwords longer than 15 characters, and for some reason the iOS client wouldn't accept the credentials even though they were correct.

logging into the game with my Google account and going through the motion of starting a new character and accepting ToS corrected it.

**Comment by timlinde** [comment]
On your account then no matter what kind you registered with.
