### ISSUE TITLE
Weird errors displaying while running runserver.py

### ISSUE THREAD

**Issue by darkdefiled** [PokemonGoMap/PokemonGo-Map#181]
## Expected Behavior
should work as how its designed right?

## Current Behavior

2016-08-08 19:24:50,200 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 0)
2016-08-08 19:24:50,203 [ search_worker_0][        search][   ERROR] Exception in search_worker:
Traceback (most recent call last):
  File "C:\Users\Danny\Desktop\Desktop-New-PokeMap\pogom\search.py", line 225, in search_worker_thread
    check_login(args, account, api, step_location)
  File "C:\Users\Danny\Desktop\Desktop-New-PokeMap\pogom\search.py", line 272, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "E:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError

## Possible Solution
I have no idea help me?

## Steps to Reproduce (for bugs)
1. cloned the project
2. ran npm install and npm run build
3. made a bat file with the details needed
4. output is that crappy error and no scans at all

## Context
I can't run the Scanner

## Your Environment
Python 2.7
Windows 10

**Comment by tsuncp** [comment]
first

pip install --upgrade setuptools

then install this

https://www.microsoft.com/en-us/download/details.aspx?id=44266

then follow the guide

https://pgm.readthedocs.io/en/develop/basic-install/index.html

**Comment by darkdefiled** [comment]
Alright gonna try that :)

**Comment by darkdefiled** [comment]
Issue resolved after following @tsuncp directions.
