### ISSUE TITLE
 Exception on /static/dist/js/app.min.js 

### ISSUE THREAD

**Issue by Toetje585** [PokemonGoMap/PokemonGo-Map#192]
Exception on /static/dist/js/app.min.js 

## Expected Behavior

No error

## Current Behavior

2016-08-08 20:38:05,826 [   Thread-767898][           app][   ERROR] Exception on /static/dist/js/app.min.js [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/dist-packages/playhouse/flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')

## Your Environment

Python 2.7
Ubuntu 16

**Comment by Infernoman** [comment]
Duplicate issue. Please close this issue, and reference https://github.com/PokemonGoMap/PokemonGo-Map/issues/71
