### ISSUE TITLE
peewee.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by zvvyt** [PokemonGoMap/PokemonGo-Map#198]
## Expected Behavior
Work like a charm, as per usual. 

## Current Behavior
```
2016-08-08 19:05:09,853 [      MainThread][        models][    INFO] Connecting to local SQLite database
Traceback (most recent call last):
  File "runserver.py", line 136, in <module>
    create_tables(db)
  File "/home/pi/PoGO-MAP/PokemonGo-Map/pogom/models.py", line 438, in create_tables
    db.connect()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3658, in _connect
    conn = sqlite3.connect(database, **kwargs)
peewee.OperationalError: unable to open database file
```

## My setup and background info
I'm running, and have sucessfully ran this program up until this error, on my RPI 3.
Received this error after I pulled an update of the repo w/o sudo yesterday. That shouldn't have caused it, since I've had it set up again afterwards (and since it seem to be something w/ python). 
Been searching with light and torch, but I seem to be the 'only one' to have stumbled upon this kind of issue. Most likely because it's not a real issuse, and more just me being a noob..
Not using any kind of database according to config.ini.

**Comment by Infernoman** [comment]
if you've pulled with sudo in the past you need to continue pulling with sudo or there will be permissions errors, Try pulling the repo with sudo again.

**Comment by chuyskywalker** [comment]
As noted, this is most likely an issue with your environment, not this codebase. As this is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by zvvyt** [comment]
@Infernoman I have. I've even started over, gone through the wiki w/ sudo, but I keep getting back to this error somehow.. 😕
