### ISSUE TITLE
Support in-memory SQLite database

### ISSUE THREAD

**Issue by cdhowie** [PokemonGoMap/PokemonGo-Map#203]
For smaller installs, particularly those not shared and/or fixed around the same region, it might be advantageous to allow an in-memory SQLite database to be used.  This can be accomplished by using the special filename `:memory:` when opening the database.

While this works at first, there are soon errors like this:

```
[2016-08-08 15:27:16,766] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pogomap/src/PokemonGo-Map/pogom/app.py", line 90, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "/home/pogomap/src/PokemonGo-Map/pogom/models.py", line 96, in get_active
    for p in query:
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such table: pokemon
```

I'm guessing that the software uses multiple SQLite handles to the same on-disk file, as this absolves the need of each thread to do any explicit locking; the SQLite library will use its own `flock()`-based mutex mechanism to prevent multiple threads from stepping on each other.  However, accessing an in-memory database can't work like this; all the threads need access to the same database handle and will have to exclusively lock while accessing the database to prevent corruption and/or segfaults.

This feature is particularly useful for those of us running several small maps without any real need for persistence between runs.  While each DB is only a few MB, the constant disk I/O from the many different processes quickly eats up all of my available disk bandwidth, particularly considering that each write transaction commit causes an `fsync()`, which means the disk can't even buffer writes.  Running MySQL would resolve the problem... but then I need to install MySQL alongside PostgreSQL, and, again, I don't actually need any data to persist between runs.

For now, I am working around this issue by storing the databases in `/dev/shm` (a ramdisk).

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
