### ISSUE TITLE
Partially working

### ISSUE THREAD

**Issue by Nokoa** [PokemonGoMap/PokemonGo-Map#217]
```
2016-08-08 13:52:50,177 [ search_worker_3][        search][   ERROR] Search step 138 map parsing failed, retrying request in 0 seconds
Traceback (most recent call last):
  File "C:\Users\Shahar\Desktop\PokemonGo-Map-develop\pogom\search.py", line 242, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "C:\Users\Shahar\Desktop\PokemonGo-Map-develop\pogom\models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
```
It finds pokemons but I am getting errors for some reasons.

**Comment by Somnium42** [comment]
you have to accept the terms of service with every account first.

**Comment by Nokoa** [comment]
Okay, dumb question, where is the accept button?
https://i.gyazo.com/0cd8b040c339528584b89b4edccd2b5a.png

**Comment by Infernoman** [comment]
https://github.com/TachyonRSA/PoGoTos Please close this duplicate issue.
