### ISSUE TITLE
[   ERROR] Exception in search_worker

### ISSUE THREAD

**Issue by nsttu** [PokemonGoMap/PokemonGo-Map#223]
I get the following error when i try to start.
I have the issue on the dev and on the release version.

python --version
Python 2.7.6
pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)

ill start with the following: 
python ./runserver.py -a google -u **************@gmail.com -p ******* -l "Riete 36, 9406 HG Assen" -fl -H 0.0.0.0 -P 80 -k MY_TOP_SECRET_API_KEY

2016-08-08 23:33:34,510 [ search_worker_0][        search][    INFO] Search step 373 beginning (queue size is 24)
^C2016-08-08 23:33:34,511 [ search_worker_0][        search][   ERROR] Exception in search_worker:
Traceback (most recent call last):
  File "/opt/new/PokemonGo-Map-2.2.0/pogom/search.py", line 219, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/opt/new/PokemonGo-Map-2.2.0/pogom/search.py", line 266, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "/opt/dev/PokemonGo-Map/src/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError

can someone help m

**Comment by Crazy-Clown** [comment]
What if you add in the -st and -sd arguments?

**Comment by marauder37** [comment]
For installation or configuration help please visit https://discord.gg/nXyMej6 . Github issues are only for issues/bugs in the code. Thanks!
