### ISSUE TITLE
Unable to run the server (KeyError)

### ISSUE THREAD

**Issue by Amoki** [PokemonGoMap/PokemonGo-Map#246]
Unable to run the server (KeyError)
## Expected Behavior
Be able to start the server

## Current Behavior
```
$ python ./runserver.py -a ptc -u $USERNAME -p "$PASSWORD" -l "$LOC" -st 3 -k "$MAP_KEY"
2016-08-09 00:56:00,524 [      MainThread][     utilities][    INFO] Location for ''MY LOCATION'' found: MY LOCATION WITH ZIPCODE
2016-08-09 00:56:00,540 [      MainThread][     utilities][    INFO] Coordinates (lat/long/alt) for location: THE GOOD GPS COORD
2016-08-09 00:56:05,009 [      MainThread][     runserver][    INFO] Parsed location is: THE GOOD GPS COORD/14.8553 (lat/lng/alt)
2016-08-09 00:56:05,024 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-09 00:56:05,040 [   search_thread][        search][    INFO] Search overseer starting
2016-08-09 00:56:05,055 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-09 00:56:05,071 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-09 00:56:05,071 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 0)
2016-08-09 00:56:05,071 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: USERNAME
2016-08-09 00:56:07,898 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-09 00:56:07,898 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-09 00:56:08,338 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-09 00:56:09,901 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds
Traceback (most recent call last):
  File "/home/amoki/pokemon/PokemonGo-Map/pogom/search.py", line 242, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/home/amoki/pokemon/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
```

## Steps to Reproduce (for bugs)

1. ``` $ python ./runserver.py -a ptc -u $USERNAME -p "$PASSWORD" -l "$LOC" -st 3 -k "$MAP_KEY"```

## Your Environment

* Version used:  commit 372878d5eaf56db4e6ec1e128a9efb7bdc17bdf6
* Environment name and version (e.g. Python 2.7): 
  * Python 2.7.6
  * pip freeze (with virtual env):
```
alabaster==0.7.9
argh==0.26.2
Babel==2.3.4
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
certifi==2016.8.8
click==6.6
CommonMark==0.5.4
ConfigArgParse==0.10.0
docutils==0.12
Flask==0.11.1
Flask-Compress==1.3.0
Flask-Cors==2.1.2
future==0.15.2
geopy==1.11.0
gpsoauth==0.3.0
imagesize==0.7.1
itsdangerous==0.24
Jinja2==2.8
LatLon==1.0.1
livereload==2.4.1
MarkupSafe==0.23
pathtools==0.1.2
peewee==2.8.1
pgoapi==1.1.6
port-for==0.3.1
protobuf==3.0.0
pycryptodomex==3.4.2
Pygments==2.1.3
PyMySQL==0.7.5
pyproj==1.9.5.1
pytz==2016.6.1
PyYAML==3.11
recommonmark==0.4.0
requests==2.10.0
s2sphere==0.2.4
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.4.5
sphinx-autobuild==0.6.0
sphinx-rtd-theme==0.1.9
tornado==4.4.1
watchdog==0.8.3
Werkzeug==0.11.10
xxhash==0.6.1
```
* Operating System and version (desktop or mobile):
  * Windows 10, using BashOnWindows (basically an Ubuntu 14.04)

**Comment by AndrewYoungs** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/178#issuecomment-238399886

**Comment by Amoki** [comment]
Thanks!

**Comment by AndrewYoungs** [comment]
No worries :)
