### ISSUE TITLE
['GET_MAP_OBJECTS']['map_cells'] error

### ISSUE THREAD

**Issue by visualjazz-sbrunno** [PokemonGoMap/PokemonGo-Map#256]
After some of today's latest changes i seem to be getting these errors now.

```
Traceback (most recent call last):
  File "D:\Projects\pokemonmap\pogom\search.py", line 242, in search_worker_thread parse_map(response_dict, step_location)
  File "D:\Projects\pokemonmap\pogom\models.py", line 296, in parse_map cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells'] KeyError: 'map_cells'

2016-08-09 14:17:09,793 [ search_worker_2][rpc_api][INFO] Error - something strange happend...

2016-08-09 14:17:09,795 [ search_worker_2][search][ WARNING] Exception while downloading map: list index out of range
```

Some pokemon are showing up still, but not sure if you are wanting more info let me know!

**Comment by visualjazz-sbrunno** [comment]
This seems to have fixed with latest commit.

_Multiply max db connections by number of accounts (threads) used (#239)_

Will let you know if anything happens again but looks good so far!
