### ISSUE TITLE
can't install the requirements

### ISSUE THREAD

**Issue by abratar** [PokemonGoMap/PokemonGo-Map#276]
How can I install the requirements if it doesn't work? I mean when i type pip install -r requirements.txt it just runs until this pgoapi or whatever and it says it can't find the file... why would it even download to my temp folder?... I used 2 pcs and on both it doesnt work... Can I download it manually? but where do i need to put it in? in what folder?

**Comment by cyrillc** [comment]
Can't install requirements either. though it has a different error.

```
E:\code\projects\PokemonGo-Map>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in c:\users\fabian\anaconda3\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\users\fabian\anaconda3\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\users\fabian\anaconda3\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\users\fabian\anaconda3\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\users\fabian\anaconda3\lib\site-packages (from -r requirements.txt (line 5))
Collecting configargparse==0.10.0 (from -r requirements.txt (line 6))
  Using cached ConfigArgParse-0.10.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\users\fabian\anaconda3\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\users\fabian\anaconda3\lib\site-packages (from -r requirements.txt (line 8))
Collecting peewee==2.8.1 (from -r requirements.txt (line 9))
  Using cached peewee-2.8.1.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 10))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Fabian\AppData\Local\Temp\pip-build-39ub5g3t\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "c:\users\fabian\appdata\local\temp\pip-build-39ub5g3t\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Fabian\AppData\Local\Temp\pip-build-39ub5g3t\wsgiref\
```

**Comment by rlex** [comment]
@cyrillc are you using python 3.x?

**Comment by cyrillc** [comment]
yes.

**Comment by cyrillc** [comment]
Same Error with 2.7

**Comment by andrejborstnik** [comment]
@cyrillc if you get the same error you are using python 3.x
if you have both installed try ```pip2 install -r requirements.txt```

**Comment by cyrillc** [comment]
Totally forgot about that... thanks mate!

**Comment by c0ver** [comment]
I have the same problem. Is there a fix?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
