### ISSUE TITLE
"Search step N area download failed retrying request in M seconds" issue

### ISSUE THREAD

**Issue by san4a** [PokemonGoMap/PokemonGo-Map#291]
**Expected Behavior:**
Application works and the map shows pokemons.

**Current Behavior:**
There are no pokemons on the map and the following errors can be seen in console log:

"2016-08-09 15:05:49,115 [ search_worker_0][        search][   ERROR] Search step 7 area download failed, retrying request in 30 seconds
2016-08-09 15:06:19,109 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: fcmkh1925
2016-08-09 15:06:19,868 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-09 15:06:19,869 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-09 15:06:20,055 [ search_worker_0][      auth_ptc][    INFO] PTC AccessToken successfully retrieved.
2016-08-09 15:06:41,079 [ search_worker_0][        search][   ERROR] Search step 7 area download failed, retrying request in 40 seconds
2016-08-09 15:07:21,065 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: fcmkh1925
2016-08-09 15:07:21,828 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-09 15:07:21,828 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-09 15:07:22,013 [ search_worker_0][      auth_ptc][    INFO] PTC Access
Token successfully retrieved.
2016-08-09 15:07:43,039 [ search_worker_0][        search][   ERROR] Search step 7 area download failed, retrying request in 50 seconds
2016-08-09 15:08:33,019 [ search_worker_0][        search][   ERROR] Search step 7 went over max scan_retires; abandoning"

Please see screenshot in attachment.
![untitled](https://cloud.githubusercontent.com/assets/13852024/17515862/9f1069f8-5e43-11e6-95fa-9267820b8b61.png)

**Steps to Reproduce (for bugs)**
1. Install the application.
2. Run "python runserver.py -a ptc -u fcmkh1925 -p fcmkh1925 -l "50.008201, 36.239454" -st 5 -H 0.0.0.0".
3. Check the console log and pokemon map in browser.

**Environment**
OS Windows 8.1, Python 2.7.

**Comment by johnkernke** [comment]
Accept the TOS in game (or through one of the scripts other people have written to do it)

**Comment by san4a** [comment]
I've just logged in with this account from android, accepted ToS, caught first pokemon and logged out. Issue with the map is stil reproducible :(

**Comment by Jackdepancake** [comment]
I am encountering the same issue.

**Comment by lmjustic** [comment]
https://github.com/scottstamp/pgoapi/tree/master/scripts/accept-tos.py
This script from the Pokémon Go API GitHub page will auto accept the ToS for your account(s).  Simply modify line 25 with the credentials and run the script.  The map should work afterwards.

**Comment by san4a** [comment]
I've already run this script and moreover I've logged in with this account from my android device and accepted ToS there.

**Comment by slideup-benni** [comment]
same issue here. this thorws not in all requests, but in ca. 5%. accepted tos.

**Comment by chnateag** [comment]
hi, same as you guys, accepted tos via script and try to connect the game + catch 1 pok, stil got the issue

**Comment by cichacz** [comment]
@chnateag this warning is related to encryption library you're using. what OS are you on?
Also what is the output of `ldd --version` command?

**Comment by andrewli-ca** [comment]
accepted the TOS for all my accounts and I still get the error

**Comment by smokedcow** [comment]
I get a similar error message,but I only get the error message with accounts created after the API changed (around August 3rd), all of my older accounts still work. I have verified the email address, and accepted the TOS using the above mentioned script.

The error get is the following:

Search step 1 map parsing failed, retrying request in 10 seconds
Traceback (most recent call last):
  File "/home/pi/Poke/PokemonGo-Map-developT/pogom/search.py", line 242, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/pi/Poke/PokemonGo-Map-developT/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
