### ISSUE TITLE
Login Issue: Attribute Error

### ISSUE THREAD

**Issue by trippyhat** [PokemonGoMap/PokemonGo-Map#312]
## Expected Behavior
Set username/password in config.ini

## Current Behavior
Fails with error:

```
2016-08-09 11:15:34,910 [ search_worker_0][        search][   ERROR] Exception in search_worker: 
Traceback (most recent call last):
  File "/home/hay/poke/new/PokemonGo-Map/pogom/search.py", line 225, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/home/hay/poke/new/PokemonGo-Map/pogom/search.py", line 272, in check_login
    api.set_authentication(provider=account['auth_service'], username=account['username'], password=account['password'])
  File "/home/hay/poke/PokemonGo-Map/src/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError
```
## Steps to Reproduce (for bugs)

Install requirements:

```
pip install -r requirements.txt
```

My config file:

```
# Authentication settings
#auth-service:          # ptc (default) or google
username: myusername
password: mypassword

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
location: new york, ny
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#scan-delay:            # default 10
step-limit:5

# Misc
gmaps-key: xxxxxxxx
#webhook:               # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)
#locale:                # pokemon translation

```

Then run:

```
python runserver.py
```
**NOTE**: I have already accepted TOS too.

## Context
Cannot use application

## Your Environment
python 2.7, Ubuntu 16.04

**Comment by crckdns** [comment]
did you confirm the account itself? (if it is a google account, you have to confirm the eMail address you've entered on creation)

**Comment by A33a** [comment]
the problem is with pgoapi. Run the command "pip show pgoapi". If the "Location" of it is some of your previous project clones, just delete that clone folder. And run "sudo pip install -r requirements.txt" again

**Comment by trippyhat** [comment]
@A33a Yes, you are right. Did that and I can now log in.
