### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by mlfactory** [PokemonGoMap/PokemonGo-Map#314]
Hello,

the script dont working since 2 houres anymore.

Error:

```
Traceback (most recent call last):
  File "./runserver.py", line 75, in <module>
    position = util.get_pos_by_name(args.location)
  File "/root/newpoke/PokemonGo-Map/Tools/Easy-Setup/src/pgoapi/pgoapi/utilities.py", line 62, in get_pos_by_name
    loc = geolocator.geocode(location_name, timeout=10)
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/base.py", line 171, in _call_geocoder
    raise GeocoderServiceError(message)
geopy.exc.GeocoderServiceError: <urlopen error [Errno -2] Name or service not known>
```

Whats the Problem?
Thanks

**Comment by invisiblek** [comment]
support on discord, check the wiki
