### ISSUE TITLE
KeyError: 'map_cells'

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoMap/PokemonGo-Map#319]
```python runserver.py -a ptc -u ....... -p ..... -k "AIzaSyDE8KRBJezC44QKX_UYu2wXWQ8w-kUMk" -st 5 -l "Sydney, New South Wales, Australia"

2016-08-10 01:23:35,156 [      MainThread][     utilities][    INFO] Location for 'Sydney, New South Wales, Australia' found: Sydney NSW, Australia
2016-08-10 01:23:35,156 [      MainThread][     utilities][    INFO] Coordinates (lat/long/alt) for location: -33.8688197 151.2092955 0.0
2016-08-10 01:23:35,200 [      MainThread][     runserver][    INFO] Parsed location is: -33.8688/151.2093/24.5399 (lat/lng/alt)
2016-08-10 01:23:35,203 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-10 01:23:35,206 [   search_thread][        search][    INFO] Search overseer starting
2016-08-10 01:23:35,206 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-10 01:23:35,208 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-10 01:23:35,215 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 3)
2016-08-10 01:23:35,215 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: hehehihihi
2016-08-10 01:23:37,297 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-10 01:23:37,297 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-10 01:23:39,785 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-10 01:23:40,292 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds
Traceback (most recent call last):
  File "/home/PokemonGo-Map/pogom/search.py", line 242, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/PokemonGo-Map/pogom/models.py", line 299, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-10 01:23:50,565 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 20 seconds
Traceback (most recent call last):
  File "/home/PokemonGo-Map/pogom/search.py", line 242, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/PokemonGo-Map/pogom/models.py", line 299, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'```
## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:centos6
* Environment name and version (e.g. Python 2.7): python2.72
* Operating System and version (desktop or mobile):

**Comment by crckdns** [comment]
I've had this error with a new account which hadn't accepted the ToS yet, just guessing

**Comment by rubenkl89** [comment]
duplicate #275, accept ToS

**Comment by cbogithub** [comment]
thanks
