### ISSUE TITLE
Configure External Access

### ISSUE THREAD

**Issue by ipedromartins** [PokemonGoMap/PokemonGo-Map#373]
I configured my router and I can not use my port and IP 

```
2016-08-09 21:51:01,190 [      MainThread][     runserver][    INFO] Parsed location is: -14.7874/-39.2750/60.3702 (lat/lng/alt)
2016-08-09 21:51:01,197 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-09 21:51:01,210 [   search_thread][        search][    INFO] Search overseer starting
2016-08-09 21:51:01,210 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-09 21:51:01,213 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-09 21:51:01,214 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 0)
2016-08-09 21:51:01,217 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: naosei2547
Traceback (most recent call last):
  File "C:\Users\Pedro Martins\Desktop\Pokemon Mapa\PokemonGo-Map\runserver.py", line 180, in <module>
    app.run(threaded=True, use_reloader=False, debug=args.debug, host=args.host, port=args.port)
  File "C:\Python27\lib\site-packages\flask\app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
    inner()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 656, in inner
    fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "C:\Python27\lib\SocketServer.py", line 417, in __init__
    self.server_bind()
  File "C:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "C:\Python27\lib\SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10049] O endereþo solicitado nÒo Ú vßlido no contexto
```

**Comment by FrostTheFox** [comment]
What have you put in for -H or the host setting?

**Comment by Kruptein** [comment]
The ip you provide for the -H host flag has to be your local/internal ip not your external ip.

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
