### ISSUE TITLE
KeyError: 'map_cells' in models.py

### ISSUE THREAD

**Issue by JoeSham** [PokemonGoMap/PokemonGo-Map#429]
2016-08-10 17:55:14,381 [      MainThread][     runserver][    INFO] Parsed location is: 49.2046/16.5951/245.8451 (lat/lng/alt)
2016-08-10 17:55:14,384 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-10 17:55:14,400 [   search_thread][        search][    INFO] Search overseer starting
2016-08-10 17:55:14,400 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-10 17:55:14,414 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-10 17:55:14,414 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 0)
2016-08-10 17:55:14,430 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: EeveeBrno
2016-08-10 17:55:15,016 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-10 17:55:15,016 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-10 17:55:15,184 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-10 17:55:16,086 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds
Traceback (most recent call last):
  File "d:\PokemonGo\PokemonGo-Map\pogom\search.py", line 245, in search_worker_thread
    parse_map(response_dict, step_location)
  File "d:\PokemonGo\PokemonGo-Map\pogom\models.py", line 299, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

(Then it keeps on going show the same error for step 2 etc.)

I am new to this. Not sure if it is a bug or if I did something wrong, but I followed the tutorial to the point as far as I am aware. Thank you.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
