### ISSUE TITLE
Google accounts: SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by Dagothur** [PokemonGoMap/PokemonGo-Map#436]
This error spams on my workers that use google accounts:

2016-08-10 13:27:20,905 [ search_worker_0][        search][   ERROR] Exception in search_worker: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Traceback (most recent call last):
  File "/root/pogo_updated/PokemonGo-Map-develop/pogom/search.py", line 228, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/root/pogo_updated/PokemonGo-Map-develop/pogom/search.py", line 281, in check_login
    api.set_authentication(provider=account['auth_service'], username=account['username'], password=account['password'])
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 82, in set_authentication
    self._auth_provider.user_login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/auth_google.py", line 55, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by Akivas** [comment]
Hello, 

This worked for me (I assume you are on Debian Wheezy ?) : 
```
pip uninstall -y certifi && pip install certifi==2015.04.28
```

**Comment by Dagothur** [comment]
Correct. This worked. Thanks!
