### ISSUE TITLE
Using -dc causes error

### ISSUE THREAD

**Issue by 360bladez** [PokemonGoMap/PokemonGo-Map#451]
when I add the -dc flag when starting the server it gives error below
logs me out and has to log me back in. 
If I remove flag it works fine

openvz ubuntu 15 min fresh install
Python 2.7
npm 3.10.5
node v4.4.7

2016-08-10 12:18:35,664 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-10 12:18:35,664 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-10 12:18:35,750 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-10 12:18:36,540 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 367 pokestops, and 15 gyms
2016-08-10 12:18:45,265 [ search_worker_0][        search][    INFO] Search step 2 beginning (queue size is 89)
2016-08-10 12:18:45,455 [ search_worker_0][        search][   ERROR] Exception in search_worker: [Errno 2] No such file or directory: '/PokemonGo-Map/static/dist/data/pokemon.min.json'. Username: #####
Traceback (most recent call last):
  File "/PokemonGo-Map/pogom/search.py", line 247, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/PokemonGo-Map/pogom/models.py", line 307, in parse_map
    p['longitude'], d_t)
  File "/PokemonGo-Map/pogom/customLog.py", line 17, in printPokemon
    pokemon_name = get_pokemon_name(id).lower()
  File "/PokemonGo-Map/pogom/utils.py", line 271, in get_pokemon_name
    return i8ln(get_pokemon_data(pokemon_id)['name'])
  File "/PokemonGo-Map/pogom/utils.py", line 265, in get_pokemon_data
    with open(file_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/PokemonGo-Map/static/dist/data/pokemon.min.json'
2016-08-10 12:18:45,460 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 88)
2016-08-10 12:18:45,461 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: ####
2016-08-10 12:18:45,882 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-10 12:18:45,882 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-10 12:18:45,964 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-10 12:18:46,479 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

**Comment by WtfJoke** [comment]
Did you run grunt build?

**Comment by jorio2311** [comment]
What does the "-dc" argument?

**Comment by WtfJoke** [comment]
@jorio2311  https://github.com/PokemonGoMap/PokemonGo-Map/wiki/Command-Line-Arguments

**Comment by 360bladez** [comment]
After I ran npm run build the issue was resolved.
The wording of the guide made it sound like not to run it.
Thank you.
