### ISSUE TITLE
git update error 

### ISSUE THREAD

**Issue by noncicredo** [PokemonGoMap/PokemonGo-Map#464]
When i try to update to the latest commit, everything works fine but "pip install requirements..."
it gives me this error

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 479, in move_wheel_files
    generated.extend(maker.make(spec))
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 372, in make
    self._make_script(entry, filenames, options=options)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 276, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 250, in _write_script
    self._fileop.write_binary_file(outname, script_bytes)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/util.py", line 405, in write_binary_file
    with open(path, 'wb') as f:
IOError: [Errno 13] Permission denied: '/usr/local/bin/easy_install'

After that, i go ahead with the other commands and the procedure goes fine

Is this a real error? could it compromise the update? thanks

**Comment by Ketakku** [comment]
I'm not entirely sure, but did you remember to sudo pip install -r requirements.txt? the bottom error says permission denied so you might have forgotten to sudo, or su and then run items.

**Comment by noncicredo** [comment]
thanks for your answer dude
anyway, im on OSX and i never ''sudo'' or ''su'', all the commands i've run about this bot worked without sudo, but i'll give it a try ;)

**Comment by Ketakku** [comment]
Might be useful for the other guys who know way more than I do to put some basic system info in there, like what OS you're on. Good luck with the sudo attempts!

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
