### ISSUE TITLE
Search toggle if turned off for extended time causes issues

### ISSUE THREAD

**Issue by jtp10181** [PokemonGoMap/PokemonGo-Map#522]
## Your Environment
* Version used: develop from earlier today
https://github.com/PokemonGoMap/PokemonGo-Map/tree/442dc528d95e843117f14bfcc95a5b09bb474355

* Environment name and version: Python 2.7
* Operating System and version: Windows 7

Things like this happen any time I have the "Search" toggle switched off for a long time (couple of hours). When I turn it back on it looks like multiple threads run very quickly and then it gets throttled.

This happening on the 2.2.0 tag version also.

```
2016-08-11 11:21:58,497 [      Thread-344][           app][    INFO] Search thread paused
Exception in thread Thread-350:
Traceback (most recent call last):
  File "D:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Python27\lib\SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "D:\Python27\lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\Python27\lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Python27\lib\SocketServer.py", line 654, in __init__
    self.finish()
  File "D:\Python27\lib\SocketServer.py", line 713, in finish
    self.wfile.close()
  File "D:\Python27\lib\socket.py", line 283, in close
    self.flush()
  File "D:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine

2016-08-11 15:30:59,065 [      Thread-355][           app][    INFO] Search thread resumed
2016-08-11 15:30:59,658 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 1)
2016-08-11 15:31:00,049 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: XXXXX
2016-08-11 15:31:01,220 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-11 15:31:01,283 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-11 15:31:01,486 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-11 15:31:03,285 [ search_worker_0][        models][    INFO] Upserted 1 pokemon, 16 pokestops, and 5 gyms
2016-08-11 15:31:03,285 [ search_worker_0][        search][    INFO] Search step 2 beginning (queue size is 17)
2016-08-11 15:31:03,440 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-11 15:31:03,440 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 16)
2016-08-11 15:31:03,565 [ search_worker_0][        search][ WARNING] Exception while downloading map: Request throttled by server... slow do
wn man
2016-08-11 15:31:03,565 [ search_worker_0][        search][   ERROR] Search step 3 area download failed, retrying request in 10 seconds
2016-08-11 15:31:13,769 [ search_worker_0][        models][    INFO] Upserted 1 pokemon, 17 pokestops, and 5 gyms
2016-08-11 15:31:13,769 [ search_worker_0][        search][    INFO] Search step 4 beginning (queue size is 15)
2016-08-11 15:31:13,894 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-11 15:31:13,894 [ search_worker_0][        search][    INFO] Search step 5 beginning (queue size is 14)
2016-08-11 15:31:14,019 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-11 15:31:14,019 [ search_worker_0][        search][    INFO] Search step 6 beginning (queue size is 13)
2016-08-11 15:31:14,114 [ search_worker_0][        search][ WARNING] Exception while downloading map: Request throttled by server... slow do
wn man
2016-08-11 15:31:14,114 [ search_worker_0][        search][   ERROR] Search step 6 area download failed, retrying request in 10 seconds
2016-08-11 15:31:24,286 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 15 pokestops, and 5 gyms
2016-08-11 15:31:24,286 [ search_worker_0][        search][    INFO] Search step 7 beginning (queue size is 12)
2016-08-11 15:31:24,411 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-11 15:31:24,411 [ search_worker_0][        search][    INFO] Search step 8 beginning (queue size is 11)
2016-08-11 15:31:24,551 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-11 15:31:24,551 [ search_worker_0][        search][    INFO] Search step 9 beginning (queue size is 10)
2016-08-11 15:31:24,661 [ search_worker_0][        search][ WARNING] Exception while downloading map: Request throttled by server... slow do
wn man
2016-08-11 15:31:24,661 [ search_worker_0][        search][   ERROR] Search step 9 area download failed, retrying request in 10 seconds
2016-08-11 15:31:29,221 [      Thread-369][           app][    INFO] Search thread paused
2016-08-11 15:31:34,911 [ search_worker_0][        models][    INFO] Upserted 2 pokemon, 17 pokestops, and 5 gyms

```

**Comment by nnpoke** [comment]
Same as #456

**Comment by jtp10181** [comment]
Sorry, I looked through all the issues before I posted it, not sure how I missed yours.
