### ISSUE TITLE
active_fort_modifier

### ISSUE THREAD

**Issue by aididhaiqal** [PokemonGoMap/PokemonGo-Map#539]
## Expected Behavior
On my other 4 instance (-ns) no error message to be found but on instance with error message is happned frontend

## Current Behavior
2016-08-12 11:44:08,490 [search_worker_10][        search][   ERROR] Exception in search_worker: local variable 'active_fort_modifier' referenced before assignment. Username: LKycmSaC2dn7C1x
Traceback (most recent call last):
  File "C:\Users\aidid\Desktop\Pokemon GO Map\pogom\search.py", line 253, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Users\aidid\Desktop\Pokemon GO Map\pogom\models.py", line 367, in parse_map
    'active_fort_modifier': active_fort_modifier,
UnboundLocalError: local variable 'active_fort_modifier' referenced before assignment

## Your Environment

* Version used: Latest
* Environment name and version (e.g. Python 2.7): 2.7.12
* Operating System and version (desktop or mobile):Desktop

**Comment by DoktorJ** [comment]
Duplicate of #515 ?

**Comment by aididhaiqal** [comment]
Solved with my PR
