### ISSUE TITLE
Error after I have reinstalled my server

### ISSUE THREAD

**Issue by Jordan318** [PokemonGoMap/PokemonGo-Map#547]
Hello, 

I have reinstalled pogo-map for update (many errors with `git pull`) and when I start the server with this comand line:

python runserver.py -a ptc -u Account1 -u Account2 -u Account3 -u Account4 -u Account5 -p pass1 -p pass2 -p pass3 -p pass4 -p pass5 -l "48.855449, 2.325926" -st 5 -sd 10 -H 0.0.0.0

I have this error:

2016-08-12 09:49:21,422 [      MainThread][     runserver][    INFO] Parsed location is: 48.2860/6.9493/339.1687 (lat/lng/alt)
2016-08-12 09:49:21,426 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-12 09:49:21,434 [   search_thread][        search][    INFO] Search overseer starting
2016-08-12 09:49:21,434 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-12 09:49:21,450 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-12 09:49:21,451 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 60)
2016-08-12 09:49:21,452 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: Account1
2016-08-12 09:49:22,134 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-12 09:49:22,134 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-12 09:49:22,278 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-12 09:49:23,101 [ search_worker_0][        search][   ERROR] Exception in search_worker: local variable 'active_fort_modifier' referenced before assignment. Username: Account1
Traceback (most recent call last):
  File "/home/pokemon/PokemonGo-Map-develop/PokemonGo-Map/pogom/search.py", line 247, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/pokemon/PokemonGo-Map-develop/PokemonGo-Map/pogom/models.py", line 364, in parse_map
    'active_fort_modifier': active_fort_modifier,

**Comment by Jordan318** [comment]
solved

cd ..
cd PokemonGo-Map

And it's works now (don't know why...)
