### ISSUE TITLE
mysql errors , in stable release after updating development branch (using both versions on same database in windows)

### ISSUE THREAD

**Issue by UwV2000** [PokemonGoMap/PokemonGo-Map#548]
## Expected Behavior
No errors

## Current Behavior
1.
This error after issuing cmd ./runserver  in stable version : 

2016-08-12 10:32:56,075 [      MainThread][     runserver][    INFO] Parsing of Pokestops disabled
2016-08-12 10:32:56,081 [      MainThread][     runserver][    INFO] Parsing of Gyms disabled
2016-08-12 10:32:56,088 [      MainThread][        models][    INFO] Connecting to MySQL database on someipinmylocalnetwork:3306
2016-08-12 10:32:56,137 [   search_thread][        search][    INFO] Search overseer starting
2016-08-12 10:32:56,217 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-12 10:32:56,223 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-12 10:32:56,227 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 0)
2016-08-12 10:32:56,236 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: USEDUSER
2016-08-12 10:32:57,536 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-12 10:32:57,539 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-12 10:32:57,694 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-12 10:32:59,569 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
C:\Python27\lib\site-packages\pymysql\cursors.py:161: Warning: Data truncated for column 'scanned_id' at row 1
  result = self._query(query)

2,
No  scanned locations showing on map from that instance  except that first step

3.
This error in console when calling 'stable' website : 

[2016-08-12 10:11:18,571] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\PokemonGo-Map(5001)\pogom\app.py", line 93, in raw_data
    d['pokestops'] = Pokestop.get_stops(swLat, swLng, neLat, neLng)
  File "C:\PokemonGo-Map(5001)\pogom\models.py", line 213, in get_stops
    for p in query:
  File "C:\Python27\lib\site-packages\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\playhouse\shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 161, in execute
    result = self._query(query)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 317, in _query
    conn.query(q)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1021, in _read_query_result
    result.read()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 983, in _read_packet
    packet.check_error()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1054, u"Unknown column 't1.active_pokemon_id' in 'field list'")
2016-08-12 10:11:18,571 [        Thread-4][           app][   ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\PokemonGo-Map(5001)\pogom\app.py", line 93, in raw_data
    d['pokestops'] = Pokestop.get_stops(swLat, swLng, neLat, neLng)
  File "C:\PokemonGo-Map(5001)\pogom\models.py", line 213, in get_stops
    for p in query:
  File "C:\Python27\lib\site-packages\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\playhouse\shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 161, in execute
    result = self._query(query)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 317, in _query
    conn.query(q)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1021, in _read_query_result
    result.read()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 983, in _read_packet
    packet.check_error()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1054, u"Unknown column 't1.active_pokemon_id' in 'field list'")

dev branch still works 

## Possible Solution
fix "scanned_id" getting a 2 digit value in DB ? 

## Steps to Reproduce (for bugs)
1.  use mysql
2.  use stable and updated develop branch
3.  run both on same DB  
4.  see output in console/cmd

## Your Environment

* Version used:  2.2.0(stable) /  develop (last pull/build about 20 mins. back)
* Python 2.7
* Windows 10 x64

**Comment by smc87** [comment]
Same issue

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
