### ISSUE TITLE
ERROR Map parsing failed

### ISSUE THREAD

**Issue by badubiduba** [PokemonGoMap/PokemonGo-Map#557]
I am using 6 workers and 2 are failing with the following message:

Map parsing failed

Any idea why?

**Comment by Erliz** [comment]
the same to me.
```
2016-08-12 12:16:53,941 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 20 seconds
Traceback (most recent call last):
  File "/usr/src/app/pogom/search.py", line 247, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/usr/src/app/pogom/models.py", line 310, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
```
`accept-tos.py` already run. Yesterday all worked =(

**Comment by divnotded** [comment]
same  3 map parsing failed, retrying request in 10 seconds
Traceback (most recent call last):
  File "C:\Users\Mark\Desktop\pokemon map88\PokemonGo-Map\pogom\search.py", line
 247, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Users\Mark\Desktop\pokemon map88\PokemonGo-Map\pogom\models.py", line
 299, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-12 05:40:25,332 [ search_worker_3][        search][   ERROR] Search step
 4 map parsing failed, retrying request in 10 seconds
Traceback (most recent call last):
  File "C:\Users\Mark\Desktop\pokemon map88\PokemonGo-Map\pogom\search.py", line
 247, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Users\Mark\Desktop\pokemon map88\PokemonGo-Map\pogom\models.py", line
 299, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by aschnebe** [comment]
Same issue here.

**Comment by martip-sainsburys** [comment]
Same here

**Comment by vinsevinalon** [comment]
same issue :(

**Comment by Jordan318** [comment]
same here

**Comment by heldertb** [comment]
Same here...

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by heldertb** [comment]
FYI To fix this, delete and re-install the complete program again

**Comment by mrfantomex** [comment]
same.
