### ISSUE TITLE
DB deadlocks and errors

### ISSUE THREAD

**Issue by daproject85** [PokemonGoMap/PokemonGo-Map#567]
- I am currently running 173 workers with 4 accounts each. 
- My Env 4 cores 16 Gig of ram dedicated machine
- Max SQL connection limit is 2000

the worker log is flooded with 

```
2016-08-12 19:02:26,206 [ search_worker_3][        search][   ERROR] Exception in search_worker: (1213, u'Deadlock found when trying to get lock; try restarting transaction'). Username: **<TOOK OUT MY USERNAME>**
Traceback (most recent call last):
  File "/root/Desktop/PokemonGo-Map/pogom/search.py", line 247, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/root/Desktop/PokemonGo-Map/pogom/models.py", line 412, in parse_map
    clean_database()
  File "/root/Desktop/PokemonGo-Map/pogom/models.py", line 429, in clean_database
    query.execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3274, in execute
    return self.database.rows_affected(self._execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
```

I believe this issue is with the code as my machine has adequet resources. With my server running 75% of CPU is used and i have 2 gigs of free ram so i am not hitting any resource threshold

**Comment by ImAnOwl** [comment]
I think this is rate limiting

**Comment by BaIthamel** [comment]
It's not your job to flag labels

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
