### ISSUE TITLE
Error find spawnpoint on MySQL >= 5.7 with sql_mod  ONLY_FULL_GROUP_BY

### ISSUE THREAD

**Issue by DragorWW** [PokemonGoMap/PokemonGo-Map#612]
this issue duplicate of #611

Error find spawnpoint on MySQL >= 5.7 with sql_mod  ONLY_FULL_GROUP_BY

## Current Behavior
use: Mysql, db: pokemongomapdb, os: mac os.
start webserver
output:
```
2016-08-13 19:50:41,906 [      MainThread][        models][    INFO] Connecting to MySQL database on 127.0.0.1:3306
[2016-08-13 19:50:46,840] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/DragorWW/PokemonGo-Map/pogom/app.py", line 112, in raw_data
    d['spawnpoints'] = Pokemon.get_spawnpoints(swLat, swLng, neLat, neLng)
  File "/Users/DragorWW/PokemonGo-Map/pogom/models.py", line 205, in get_spawnpoints
    return list(query)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/site-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1055, u"Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pokemongomapdb.t1.latitude' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
```
## Possible Solution
I think bug in spawnpoint calc `  File "PokemonGo-Map/pogom/models.py", line 205, in get_spawnpoints`
if disable ONLY_FULL_GROUP_BY in MySQL, it work

## Steps to Reproduce (for bugs)
1. update to last version
2. use mysql, empty db
3. start app with `python runserver.py -os -l '66.476184, 66.970366' -L 'ru' -H 0.0.0.0 -C`
4. open browser gui
5. toggle show spawnpoint in ui

## Your Environment
* OS X EL Capitan  (10.11.5)
* python2.7
* MySQL - 5.7.13 - Homebrew

**Comment by hemsleyk** [comment]
I had tons of (different) issues with 5.7 as well. Try mysql:5.6 if you're using Docker.

Currently using MariaDB w/ Galera though.

**Comment by Xcelled** [comment]
Since this is a duplicate, let's keep discussions to #611.

**Comment by hightechstl** [comment]
simply login to mysql, select your database and run SET sql_mode = '';
