### ISSUE TITLE
requirements.txt errors with protobuf-to-dic

### ISSUE THREAD

**Issue by MrG4dget** [PokemonGoMap/PokemonGo-Map#627]
Systems: Ubuntu 14.04 & Debian Jessie (RPi2)

Error generated by **protobuf-to-dict**

removing the entry from requirements.txt allows to run pip without problems.

**Comment by pyr0ball** [comment]
are you running as sudo? can you post the terminal output of the error?

**Comment by vincentchenjl** [comment]
I am having the same issue. Here is the error output. Even without the dependency, I am still able to run the server without problem.

```
Downloading/unpacking protobuf-to-dict==0.1.0 (from -r requirements.txt (line 27))
  Downloading protobuf-to-dict-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/protobuf-to-dict/setup.py) egg_info for package protobuf-to-dict
    
    Installed /tmp/pip_build_root/protobuf-to-dict/nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading http://mirrors.aliyun.com/pypi/simple/coverage/
    Best match: coverage 4.2
    Downloading http://mirrors.aliyun.com/pypi/packages/f5/47/2e39972c41eb988d551bb2da25c4ee16ea78492ec1b6ffdf09f50cd09b92/coverage-4.2.zip#md5=9841c9e1ddc862144fda3fd7e5ba5106
    Processing coverage-4.2.zip
    Writing /tmp/easy_install-vuFW3m/coverage-4.2/setup.cfg
    Running coverage-4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vuFW3m/coverage-4.2/egg-dist-tmp-hQLIaA
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    
    Installed /tmp/pip_build_root/protobuf-to-dict/coverage-4.2-py2.7-linux-x86_64.egg
    Searching for nose>=1.0
    Reading http://mirrors.aliyun.com/pypi/simple/nose/
    Best match: nose 1.3.7
    Downloading http://mirrors.aliyun.com/pypi/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
    Processing nose-1.3.7.tar.gz
    Writing /tmp/easy_install-0F9nP1/nose-1.3.7/setup.cfg
    Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0F9nP1/nose-1.3.7/egg-dist-tmp-6P4aiF
    no previously-included directories found matching 'doc/.build'
    
    Installed /tmp/pip_build_root/protobuf-to-dict/nose-1.3.7-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 852, in best_match
        dist = working_set.find(req)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 503, in find
        raise VersionConflict(dist,req)     # XXX add more info
    pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))
    Complete output from command python setup.py egg_info:
    

Installed /tmp/pip_build_root/protobuf-to-dict/nosexcover-1.0.10-py2.7.egg

Searching for coverage

Reading http://mirrors.aliyun.com/pypi/simple/coverage/

Best match: coverage 4.2

Downloading http://mirrors.aliyun.com/pypi/packages/f5/47/2e39972c41eb988d551bb2da25c4ee16ea78492ec1b6ffdf09f50cd09b92/coverage-4.2.zip#md5=9841c9e1ddc862144fda3fd7e5ba5106

Processing coverage-4.2.zip

Writing /tmp/easy_install-vuFW3m/coverage-4.2/setup.cfg

Running coverage-4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vuFW3m/coverage-4.2/egg-dist-tmp-hQLIaA

warning: no previously-included files found matching 'ci/appveyor.token'

no previously-included directories found matching 'doc/_build'

no previously-included directories found matching 'tests/eggsrc/build'

no previously-included directories found matching 'tests/eggsrc/dist'

no previously-included directories found matching 'tests/eggsrc/*.egg-info'

warning: no previously-included files matching '*.py[co]' found anywhere in distribution



Installed /tmp/pip_build_root/protobuf-to-dict/coverage-4.2-py2.7-linux-x86_64.egg

Searching for nose>=1.0

Reading http://mirrors.aliyun.com/pypi/simple/nose/

Best match: nose 1.3.7

Downloading http://mirrors.aliyun.com/pypi/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b

Processing nose-1.3.7.tar.gz

Writing /tmp/easy_install-0F9nP1/nose-1.3.7/setup.cfg

Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0F9nP1/nose-1.3.7/egg-dist-tmp-6P4aiF

no previously-included directories found matching 'doc/.build'



Installed /tmp/pip_build_root/protobuf-to-dict/nose-1.3.7-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/protobuf-to-dict/setup.py", line 25, in <module>

    'Topic :: Software Development :: Libraries :: Python Modules',

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 852, in best_match

    dist = working_set.find(req)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 503, in find

    raise VersionConflict(dist,req)     # XXX add more info

pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/protobuf-to-dict
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by AlexSterk** [comment]
I have the same problem.

**Comment by DyonR** [comment]
For me it worked by downloading protobuf-to-dict directly instead of using pip.
You can download protobuf-to-dict here;
https://github.com/benhodgson/protobuf-to-dict

run "python setup.py install" in the protobuf-to-dict folder.

**Comment by felixvd** [comment]
Instead of the above, try `pip install --upgrade six`. A line in your error log mentions a version conflict, and I have to to update it on my Ubuntu 14.04 install too.

**Comment by Yossi** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/commit/0822c09c505b806693984dedaf34b6894b661a4c

showed up here

**Comment by MrG4dget** [comment]
Worked for me:

`git clone https://github.com/benhodgson/protobuf-to-dict.git`
`cd protobuf-to-dict/`
`sudo python setup.py install`
