### ISSUE TITLE
[Windows] Problem with installing map under user account with cyrillic symbols in path

### ISSUE THREAD

**Issue by Okloks** [PokemonGoMap/PokemonGo-Map#64]
When you do pip install -r requirements.txt, some errors occuring

## Steps to Reproduce
1. Create user account with cyrillic names, for example: C:\Users\Михаил
2. Now login into this account and try to install the map.

## My Environment

* Windows 7 x64 SP1 Professional
* Python 2.7.12
* Microsoft Visual C++ Compiler for Python 2.7

## Traceback
```
C:\PortableApps\PokemonGO-Map\PokemonGo-Map>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): configargparse==0.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): PyMySQL==0.7.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): flask-compress==1.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Collecting LatLon==1.0.1 (from -r requirements.txt (line 17))
  Using cached LatLon-1.0.1-py2-none-any.whl
Collecting pgoapi from git+https://github.com/keyphact/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 18))
  Cloning https://github.com/keyphact/pgoapi.git to d:\temp\pip-build-uvbahc\pgoapi
Collecting xxhash (from -r requirements.txt (line 19))
  Downloading xxhash-0.6.1.tar.gz
Collecting sphinx==1.4.5 (from -r requirements.txt (line 20))
  Downloading Sphinx-1.4.5-py2.py3-none-any.whl (1.6MB)
    100% |################################| 1.6MB 253kB/s
Collecting sphinx-autobuild==0.6.0 (from -r requirements.txt (line 21))
  Downloading sphinx_autobuild-0.6.0-py2-none-any.whl
Collecting recommonmark==0.4.0 (from -r requirements.txt (line 22))
  Downloading recommonmark-0.4.0-py2.py3-none-any.whl
Collecting sphinx_rtd_theme==0.1.9 (from -r requirements.txt (line 23))
  Downloading sphinx_rtd_theme-0.1.9-py2-none-any.whl (693kB)
    100% |################################| 696kB 417kB/s
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 13))
Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 17))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "d:\temp\pip-build-uvbahc\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1135, in return_env
        exists),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1158, in _build_paths
        return os.pathsep.join(unique_paths)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 9: ordinal not in range(128)

```

**Comment by BaIthamel** [comment]
This is a known issue, but not one anyone has any plans to fix soon.

**Comment by invisiblek** [comment]
Yea, this isn't a bug with our app, this is a bug with pip. We can't fix it.
