### ISSUE TITLE
Spawn Location not working for mysql

### ISSUE THREAD

**Issue by mckn** [PokemonGoMap/PokemonGo-Map#648]
## Expected Behavior
When you toggle the spawn location switch in the UI scanned spawn locations should be visible (I guess).

## Current Behavior
Nothing happends and you get the following error in the log:

[       Thread-46][           app][   ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/pogom/app.py", line 112, in raw_data
    d['spawnpoints'] = Pokemon.get_spawnpoints(swLat, swLng, neLat, neLng)
  File "/app/pogom/models.py", line 205, in get_spawnpoints
    return list(query)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/site-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1055, u"Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pgomdb.t1.latitude' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

## Possible Solution
none

## Steps to Reproduce (for bugs)
1. open the map
2. toggle the spawn location switch

## Context
n/a

## Your Environment

* Version used: branch: develop commit: d77a7024e312de59089b41105bd8f2c076eccb07
* Environment name and version Python 2.7, mysql 5.7
* Operating System and version (desktop or mobile): ubuntu 16.04

**Comment by brabijan** [comment]
same here - docker + safari

**Comment by hightechstl** [comment]
I am getting the same thing on ubuntu 14.04 VPS + chrome & firefox

**Comment by NGPriest** [comment]
Would love to see a solution :D

**Comment by UwV2000** [comment]
only_full_group_by  
known issue
known solution:  enable full group by on the mysql server.

**Comment by hightechstl** [comment]
do you mean;

SET sql_mode = 'ONLY_FULL_GROUP_BY';

**Comment by UwV2000** [comment]
#611 
there someone has the same problem as you.
i was looking actually looking for an older issue with this same problem where that solution was proposed .. but my guess is ..  only_full_group_by  should be turned off.

**Comment by hightechstl** [comment]
correct.  i just tested it.  simply login to mysql, select your database
and run SET sql_mode = '';

then they will pop up in the map without issue

**Comment by Xcelled** [comment]
Can someone with MySQL test this branch? https://github.com/Xcelled/PokemonGo-Map/tree/spawnpoint_groupby

If it resolves the issue, it's a better fix.

**Comment by UwV2000** [comment]
$ git clone https://github.com/Xcelled/PokemonGo-Map.git
Cloning into 'PokemonGo-Map'...

ill give it a run ..
exactly what would you like to see tested ?

**Comment by Xcelled** [comment]
If this fixes the issue with spawnpoints and mysql.

Make sure you `$ git checkout spawnpoint_groupby` and also turn only_full_group_by back on. If the fix works, you shouldn't get the error anymore.

**Comment by UwV2000** [comment]
yeah... spawnpoint_scan is the default..  good you mentioned it .. will switch branch after build :/
I never had  only_full_group_by on actually

**Comment by UwV2000** [comment]
@Xcelled  
is it possible to discuss issues with your fork in your fork ? i cant seem to open a issue there ? or i am looking in the wrong place ..

**Comment by Toetje585** [comment]
If you want to disable permanently error sql_mode=only_full_group_by do those steps:

sudo nano /etc/mysql/my.cnf
Add this to the end of the file

[mysqld]
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

sudo service mysql restart

**Comment by Xcelled** [comment]
@UwV2000 since the only change in that branch is in reference to this issue, just post here.

**Comment by UwV2000** [comment]
just finished posting .. 1 comment on commit 58a95d1
