### ISSUE TITLE
Error search.py and models.py

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoMap/PokemonGo-Map#664]
## I try run but I receive this error:
```
[pokemon@fedora24 PokemonGo-Map] $ sh run.sh 
2016-08-14 12:18:37,208 [      MainThread][     utilities][    INFO] Location for 'Central Park NY' found: Central Park, New York, NY, USA
2016-08-14 12:18:37,209 [      MainThread][     utilities][    INFO] Coordinates (lat/long/alt) for location: 40.7711329 -73.9741874 0.0
2016-08-14 12:18:37,495 [      MainThread][     runserver][    INFO] Parsed location is: 40.7711/-73.9742/22.8524 (lat/lng/alt)
2016-08-14 12:18:37,500 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-14 12:18:37,598 [   search_thread][        search][    INFO] Search overseer starting
2016-08-14 12:18:37,752 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-14 12:18:37,753 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-14 12:18:37,759 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 9)
2016-08-14 12:18:37,759 [ search_worker_0][   auth_google][    INFO] Google User Login for: [MYEMAIL]@gmail.com
2016-08-14 12:18:38,332 [ search_worker_0][   auth_google][    INFO] Google User Login successful.
2016-08-14 12:18:38,332 [ search_worker_0][   auth_google][    INFO] Request Google Access Token...
2016-08-14 12:18:38,841 [ search_worker_0][   auth_google][    INFO] Google Access Token successfully received.
2016-08-14 12:18:40,567 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds. Username: [MYEMAIL]@gmail.com
Traceback (most recent call last):
  File "/home/carlos/Documentos/POKEMON/PokemonGo-Map/pogom/search.py", line 281, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/carlos/Documentos/POKEMON/PokemonGo-Map/pogom/models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

```
## Your Environment

* Version used:dev last ccommit
* Environment: python 2.7 
* Operating System: fedora24

**Comment by PaleHaunt** [comment]
I'm having this exact same issue today.

**Comment by Becold** [comment]
Dulicate of #632

**Comment by PaleHaunt** [comment]
Indeed. It means your account had been banned.

**Comment by omes000** [comment]
are we sure it's related to the account being banned? I tried creating a fresh account a few days ago, activated it, and immediately it would give this message.

**Comment by jussini** [comment]
I ran https://github.com/scottstamp/pgoapi/blob/master/scripts/accept-tos.py for the accounts giving the problem and it helped.

**Comment by Linwood-WP** [comment]
Yeah when one account is banned, this error appear and stop all others workers...

**Comment by UwV2000** [comment]
just tested this
and that error comes up when account is new and has not agreed to the TOS.
after going in game and agreeing with the TOS the error was gone.

**Comment by MrCarlosJr** [comment]
Yes is ToS, its simple... open new account in bot 5min.
