### ISSUE TITLE
grunt build fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by felixvd** [PokemonGoMap/PokemonGo-Map#672]
No one in the discord seemed to know a fix for this, so I'm posting it here.

## Expected Behavior
grunt should build the project like it did when I last downloaded the map two weeks ago. 

## Current Behavior
grunt build fails with this output:

```
root@server:~/PokemonGo-Map# npm install
npm WARN lifecycle pogomap@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) pogomap@0.1.0 grunt build /root/PokemonGo-Map
root@server:~/PokemonGo-Map# npm run build

> pogomap@0.1.0 build /root/PokemonGo-Map
> grunt build

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "newer:babel" (newer) task

Running "newer:babel:dist" (newer) task

Running "babel:dist" (babel) task

Running "newer-postrun:babel:dist:1:/root/PokemonGo-Map/node_modules/grunt-newer/.cache" (newer-postrun) task

Running "newer:uglify" (newer) task

Running "newer:uglify:build" (newer) task

Running "uglify:build" (uglify) task
>> 5 sourcemaps created.
>> 5 files created.

Running "newer-postrun:uglify:build:2:/root/PokemonGo-Map/node_modules/grunt-newer/.cache" (newer-postrun) task

Running "newer:sass" (newer) task

Running "newer:sass:dist" (newer) task
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/root/PokemonGo-Map/node_modules/node-sass/vendor'
Warning: Task "sass:dist" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogomap@0.1.0 build: `grunt build`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the pogomap@0.1.0 build script 'grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PokemonGo-Map/npm-debug.log
```

Earlier in my troubleshooting the Error Status has been 0. I have tried `rm -rf node_modules && npm install` without success.

## Possible Solution
Note in the doc which version of nodejs is required, maybe?

## Steps to Reproduce (for bugs)
1) Mount a server with Ubuntu 14.04
2) Follow the Basic installation steps 

## Context
I tried to reinstall the map and failed.

## Your Environment
A VPS with a fresh install of Ubuntu 14.04. My versions of nodejs and npm are v6.3.1 and 3.10.3 as noted in the log.

**Comment by priderockphi** [comment]
I encountered the exact same issue with a new install on Ubuntu 14.04 running locally on a VM.
I never solved it, I ended up running it on CentOS instead.

**Comment by tokyotapes** [comment]
try this:

ln -s /usr/bin/nodejs /usr/bin/node

**Comment by Phantisy** [comment]
I never had this issue with Ubuntu 14.04. This is the version of nodejs I am running
`nodejs -v
v0.10.25`

**Comment by felixvd** [comment]
> try this:

> ln -s /usr/bin/nodejs /usr/bin/node

```
root@server:~# ln -s /usr/bin/nodejs /usr/bin/node
ln: failed to create symbolic link '/usr/bin/node': File exists
```

> I never had this issue with Ubuntu 14.04.

How exactly did you install it? The documentation used to be more precise.

**Comment by Phantisy** [comment]
@felixvd I followed this guid.

**Comment by felixvd** [comment]
So which of those 5 options did you do? I ran `apt-get uninstall --purge node` and then followed step 1 and get this:

```
root@server:~/PokemonGo-Map# npm install
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.8.0 install /root/PokemonGo-Map/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /root/PokemonGo-Map/node_modules/node-sass/vendor/linux-x64-47/binding.node

> node-sass@3.8.0 postinstall /root/PokemonGo-Map/node_modules/node-sass
> node scripts/build.js

"/root/PokemonGo-Map/node_modules/node-sass/vendor/linux-x64-47/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
npm WARN lifecycle pogomap@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) pogomap@0.1.0 grunt build /root/PokemonGo-Map
root@server:~/PokemonGo-Map# nvm run build
No .nvmrc file found
Running node v5.0.0 (npm v3.3.6)
module.js:339
    throw err;
    ^

Error: Cannot find module '/root/PokemonGo-Map/build'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by felixvd** [comment]
Update: I wiped the server and installed node.js v6. I guess installing v4 first caused issues. grunt build now finishes without errors, but running the script gives this:

```
~/PokemonGo-Map# python ./runserver.py --help
Traceback (most recent call last):
  File "./runserver.py", line 16, in <module>
    from queue import Queue
ImportError: No module named queue
```

**Comment by felixvd** [comment]
The above came up because I forgot to install the requirements. As mentioned in #627 I have to run `pip install --upgrade six` on Ubuntu 14.04 before installing the requirements works, but that's all.

I assume that installing an old version of node.js messes up the installation and the documentation should be updated. This was really more hassle than it is worth, especially considering that the documentation _used to_ work perfectly fine.
