### ISSUE TITLE
Just stopped working

### ISSUE THREAD

**Issue by blackhattristar** [PokemonGoMap/PokemonGo-Map#680]
My map was working perfectly not more than an hour ago and then when I checked it again, no Pokémon were appearing and no "scanned locations" were appearing. So I check out my console and it returned this

`python ./runserver.py -a google -u @gmail.com -p -st 5 -sd 1 -ng -nk -k "AIzaSyClKFA2x" -l "34.009242, -118.497604" -H -P 80
2016-08-15 00:27:24,808 [      MainThread][     runserver][    INFO] Parsed location is: 34.0092/-118.4976/7.4718 (lat/lng/alt)
2016-08-15 00:27:24,808 [      MainThread][     runserver][    INFO] Parsing of Pokestops disabled
2016-08-15 00:27:24,808 [      MainThread][     runserver][    INFO] Parsing of Gyms disabled
2016-08-15 00:27:24,811 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-15 00:27:24,821 [   search_thread][        search][    INFO] Search overseer starting
2016-08-15 00:27:24,822 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-15 00:27:24,825 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-15 00:27:24,827 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 60)
2016-08-15 00:27:24,827 [ search_worker_0][   auth_google][    INFO] Google User Login for:@gmail.com
2016-08-15 00:27:25,181 [ search_worker_0][   auth_google][    INFO] Google User Login successful.
2016-08-15 00:27:25,181 [ search_worker_0][   auth_google][    INFO] Request Google Access Token...
2016-08-15 00:27:25,351 [ search_worker_0][   auth_google][    INFO] Google Access Token successfully received.
2016-08-15 00:27:25,841 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 1 seconds. Username:@gmail.com
Traceback (most recent call last):
  File "/PokemonGo-Map/pogom/search.py", line 254, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/PokemonGo-Map/pogom/models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-15 00:27:26,915 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 2 seconds. Username:@gmail.com
Traceback (most recent call last):
  File "/PokemonGo-Map/pogom/search.py", line 254, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/PokemonGo-Map/pogom/models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-15 00:27:28,989 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 3 seconds. Username:@gmail.com
Traceback (most recent call last):
  File "/PokemonGo-Map/pogom/search.py", line 254, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/PokemonGo-Map/pogom/models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-15 00:27:32,058 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 4 seconds. Username:@gmail.com
Traceback (most recent call last):
  File "/PokemonGo-Map/pogom/search.py", line 254, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/PokemonGo-Map/pogom/models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-15 00:27:36,126 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 5 seconds. Username:@gmail.com
Traceback (most recent call last):
  File "/PokemonGo-Map/pogom/search.py", line 254, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/PokemonGo-Map/pogom/models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'`
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by Cronick** [comment]
Duplicate of https://github.com/PokemonGoMap/PokemonGo-Map/issues/632

**Comment by crckdns** [comment]
the account is banned.

**Comment by blackhattristar** [comment]
@crckdns It shows right there in the log that the login was successful.

**Comment by SkOODaT** [comment]
your banned on that account i have 5 accounts doing this now out of my pool of accounts

**Comment by blackhattristar** [comment]
How could it return the same log when I try a new account that hasn't been used for scanning the map?

**Comment by SkOODaT** [comment]
are you sure you accepted the TOS ingame on the new account?

**Comment by blackhattristar** [comment]
@SkOODaT Yes.

**Comment by blackhattristar** [comment]
You guys were right and I was wrong. Looks like two of my accounts are banned. The map is back up and running with a new account. Fingers crossed that they don't catch onto this new account so quickly.

**Comment by blackhattristar** [comment]
You guys were right and I was wrong. Looks like two of my accounts are banned. The map is back up and running with a new account. Fingers crossed that they don't catch onto this new account so quickly.
