### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#708]
Exception in thread Thread-1747:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

running it with about 20 accounts and -st 5.

**Comment by antistoopmode** [comment]
I have the same issue and happens only when I deploy it on a web server, never occured locally :/

**Comment by Foxy1990** [comment]
I have exactly the same problem im getting this error every ~2 Minutes

**Comment by schadis** [comment]
i have this error also localy with my beehive ( 1 server(-os) and 18x(-ns) 7workers on step 15) spawnscanning with a mariaDB(Mysql) 
Error: Exception in thread Thread-1687 (the next same error was Thread-6441)
