### ISSUE TITLE
That's new: no map, no pokemons

### ISSUE THREAD

**Issue by LIJE** [PokemonGoMap/PokemonGo-Map#709]
Hi,

This is the first time the map doesnt show up when I run the server.
Here is what I get:

2016-08-15 20:37:14,463 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-15 20:37:14,463 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-15 20:37:14,619 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-15 20:37:15,195 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 6 seconds. Username: mcconfiance
Traceback (most recent call last):
  File "/opt/PokemonGo-Map/pogom/search.py", line 281, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/opt/PokemonGo-Map/pogom/models.py", line 330, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-15 20:37:21,495 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 12 seconds. Username: mcconfiance
Traceback (most recent call last):
  File "/opt/PokemonGo-Map/pogom/search.py", line 281, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/opt/PokemonGo-Map/pogom/models.py", line 330, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

Any way to fix this?

**Comment by m0ng3y** [comment]
Your account has been banned, use a new one.

**Comment by irus99** [comment]
Is there anything in the config for this to drop banned accounts? I don't see anything TIA

**Comment by twoLegsGood** [comment]
I'm not seeing a ban message, it only says "Failed to get game data from the server"

**Comment by Raphiki44** [comment]
It means that your account is banned : https://www.reddit.com/r/pokemongo/comments/4xcr91/failed_to_get_game_data_from_the_server/

**Comment by mfaalk** [comment]
Can confirm it's a banned account.

**Comment by LIJE** [comment]
why a fresh new account would be banned?

tried with 4 accounts

**Comment by neuhaus** [comment]
You have to log in with the app and accept the terms of service before you can use it with the scanner.

**Comment by LIJE** [comment]
I know, thats what i do evertime.

tried with a new server, a new account, same error.

**Comment by LIJE** [comment]
do you mean, this app: https://play.google.com/store/apps/details?id=com.pokemon.pokemontcg&hl=fr?
