### ISSUE TITLE
requirements.txt on ubuntu server installation error, see attached error

### ISSUE THREAD

**Issue by kuthedk** [PokemonGoMap/PokemonGo-Map#756]
I keep getting this error even though I have version 8.1.2 when I do pip --version

Collecting sphinx_rtd_theme==0.1.9 (from -r requirements.txt (line 23))
  Using cached sphinx_rtd_theme-0.1.9-py2-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by kuthedk** [comment]
never mind I fixed it by doing:
`sudo -H pip install --upgrade pip`
in the home directory
