### ISSUE TITLE
Exception in search_worker

### ISSUE THREAD

**Issue by Viper2k4** [PokemonGoMap/PokemonGo-Map#777]
## Current Behavior
Got an Exception in every worker.

2016-08-17 22:34:34,837 [ search_worker_0][        search][   ERROR] Exception in search_worker: datetime.datetime(2016, 8, 13, 20, 12, 48, 871000) is not JSON serializable. Username: xxx
Traceback (most recent call last):
  File "/home/pi/PokemonGo-Map/pogom/search.py", line 348, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/pi/PokemonGo-Map/pogom/models.py", line 456, in parse_map
    send_to_webhook('pokestop', webhook_data)
  File "/home/pi/PokemonGo-Map/pogom/utils.py", line 319, in send_to_webhook
    requests.post(w, json=data, timeout=(None, 1))
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 298, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 424, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

## Steps to Reproduce (for bugs)
1. Start Server like before :)

## Your Environment

* Version used: last git version
* Environment name and version (e.g. Python 2.7): Raspi
* Operating System and version (desktop or mobile):

**Comment by FrostTheFox** [comment]
Are you using webhooks? I'm also getting this.

**Comment by Viper2k4** [comment]
yes im using -wh

`python ./runserver.py --host 0.0.0.0 -a "ptc" -u "xxx" -p "xxx" -l "City" -st 13 -sd 10 --spawnpoints-only -k "" --port 9090 --locale "de" -fl -wh http://127.0.0.1:4000`

**Comment by FrostTheFox** [comment]
Yep, this seems to be an issue with -wh. started after I put it in my run command.

**Comment by Xcelled** [comment]
Because datetimes are not JSON serializable. http://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable-in-python

My preferred way of overcoming this is to either use an ISO formatted string, or to use a second/millisecond count like time.time()

**Comment by wschoot** [comment]
Also getting this, also using webhooks but have been using webhooks for weeks now and this just popped up. Lets see if reverting some commits helps

**Comment by FrostTheFox** [comment]
--webhook-updates-only Stops the error for me, but obviously doesn't send the new info.

**Comment by wschoot** [comment]
Reverting back to 7fdab1fef174f53891305dfa7f405f508814821b also helps, which omits all the new updateonly webhook code

**Comment by FrostTheFox** [comment]
Seb is working on a fix.

**Comment by Xcelled** [comment]
The issue was introduced here: https://github.com/PokemonGoMap/PokemonGo-Map/commit/51fd3c0cfb48975e6e4cf40f9ed5c8dda4832d43

Line 430 of models.py.

**Comment by FrostTheFox** [comment]
Correction: Is submitting a PR momentarily with a fix.

**Comment by wschoot** [comment]
Having a fix is much better than rollingback #fuckityolo  :-)

**Comment by neskk** [comment]
Just had to deal with this issue, was about to post something here... had to roll back to a previous commit and I think will leave it there for tonight ;)

**Comment by FrostTheFox** [comment]
#779 should fix. Please test.

**Comment by FrostTheFox** [comment]
Please download latest commit.

**Comment by Viper2k4** [comment]
Nope not complet gone
```
2016-08-17 23:19:21,173 [ search_worker_6][        search][   ERROR] Exception in search_worker: datetime.datetime(2016, 8, 17, 21, 24, 31, 267000) is not JSON serializable. Username: xxxx
Traceback (most recent call last):
  File "/home/pi/PokemonGo-Map/pogom/search.py", line 348, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/pi/PokemonGo-Map/pogom/models.py", line 467, in parse_map
    send_to_webhook('pokestop', webhook_data)
  File "/home/pi/PokemonGo-Map/pogom/utils.py", line 319, in send_to_webhook
    requests.post(w, json=data, timeout=(None, 1))
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 298, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 424, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 8, 17, 21, 24, 31, 267000) is not JSON serializable
```

**Comment by rrbailey89** [comment]
@FrostTheFox still broken for me too

**Comment by Viper2k4** [comment]
Ich thinks here it the change missing:

https://github.com/PokemonGoMap/PokemonGo-Map/blob/21d0fb942e4757b3e7c431ebec68ba76a3729818/pogom/models.py#L478
