### ISSUE TITLE
[ search_worker_0][        search][   ERROR] Search step 1 map parsing failed .... KeyError: 'map_cells'

### ISSUE THREAD

**Issue by d3rpd** [PokemonGoMap/PokemonGo-Map#794]
Please help. These are the logs.

2016-08-18 14:53:04,911 [      MainThread][     runserver][    INFO] Parsed location is: 10.3258/123.9199/8.5441 (lat/lng/alt)
2016-08-18 14:53:04,926 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-18 14:53:04,941 [   search_thread][        search][    INFO] Search overseer starting
2016-08-18 14:53:04,957 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-18 14:53:04,973 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-18 14:53:04,989 [   search_thread][        search][    INFO] Scan Distance is 0.07 km
2016-08-18 14:53:04,989 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 2)
2016-08-18 14:53:05,003 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: ******
2016-08-18 14:53:08,292 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-18 14:53:08,292 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-18 14:53:08,913 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-18 14:53:10,305 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds. Username: ******
Traceback (most recent call last):
  File "C:\Dev\PokemonGo-Map\pogom\search.py", line 356, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Dev\PokemonGo-Map\pogom\models.py", line 382, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by Christian-X** [comment]
KeyError 'map_cells'  shows that the user you're using is either banned or hasn't accepted TOS yet.


You should cencor your username from the log.

**Comment by d3rpd** [comment]
@Christian-X how to accept TOS? Im a beginner, please help. And what do you mean "You should cencor your username from the log."?

**Comment by Viper2k4** [comment]
how to accept TOS? By clicking "i accept the TOS" :)

But simply as it is, log in to Pokemon Go with ur Account and u will see a message that u shoult accept the Tos ;)

**Comment by d3rpd** [comment]
@Christian-X @Viper2k4
I accepted TOS now but the error is still there. Please help.

**Comment by d3rpd** [comment]
@Viper2k4 
I see. By the way, I just created that account and I can login on the site with the account.

**Comment by Christian-X** [comment]
https://www.reddit.com/r/pokemongodev/comments/4wk3e4/psa_new_pogo_accounts_have_to_accept_tos_ingame/ -- here is how you can accept the tos without submitting your phones device id from a server/pc. (I'd refrain having my device be flagged to have something to do with any bans...)

**Comment by d3rpd** [comment]
@Christian-X @Viper2k4
Thank you so much. Its working now :)

**Comment by Viper2k4** [comment]
I dont mean the site i mean the game^^. But like Christian said. The script is also working :)
