### ISSUE TITLE
Map parsing failed

### ISSUE THREAD

**Issue by slashy** [PokemonGoMap/PokemonGo-Map#798]
Just pulled the latest develop (commit 7729aab526913db84b6e967c47e8c1c13828e125) and I am getting this error:

2016-08-18 09:42:18,513 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 2 seconds. Username: ******
Traceback (most recent call last):
  File "/home/******/PokemonGo-Map/pogom/search.py", line 356, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/******/PokemonGo-Map/pogom/models.py", line 382, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by ellisio** [comment]
IP ban, throttling, or permaban on that account you are using. Try a new account.

**Comment by Dagothur** [comment]
that account is probably banned because you are probably running -st 2 (im basing this on your request retry time)

make sure u run -st 10 or higher to be safe

**Comment by Xcelled** [comment]
We really, really need to change this message. I see at least an issue a day opened about it.

**Comment by Dagothur** [comment]
i think it's an uncaught exception

**Comment by FlarumHostingCo** [comment]
Suddenly happening to me too..  If I remove a worker account that says maybe banned.. when I start runserver.py again, one that was just ok now says banned.

I took a banned account and could login and change profile info on PTC's site and I can log into game on a mobile device.

Here is console...  After workers log in, it just hangs..

2016-08-18 03:29:52,224 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 11)
2016-08-18 03:29:52,225 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: 
2016-08-18 03:29:53,157 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-18 03:29:53,157 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-18 03:29:53,223 [ search_worker_1][        search][    INFO] Search step 2 beginning (queue size is 35)
2016-08-18 03:29:53,224 [ search_worker_1][      auth_ptc][    INFO] PTC User Login for: 
2016-08-18 03:29:53,333 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-18 03:29:53,801 [ search_worker_1][      auth_ptc][    INFO] PTC User Login successful.
2016-08-18 03:29:53,801 [ search_worker_1][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-18 03:29:53,958 [ search_worker_0][        models][   ERROR] GET_MAP_OBJECTS response has 0 items - Possible Account Ban! Username: 
2016-08-18 03:29:53,959 [ search_worker_0][        models][    INFO] Pausing thread indefinitely
2016-08-18 03:29:53,960 [ search_worker_1][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-18 03:29:54,225 [ search_worker_2][        search][    INFO] Search step 3 beginning (queue size is 34)
2016-08-18 03:29:54,226 [ search_worker_2][      auth_ptc][    INFO] PTC User Login for: 
2016-08-18 03:29:54,809 [ search_worker_2][      auth_ptc][    INFO] PTC User Login successful.
2016-08-18 03:29:54,809 [ search_worker_2][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-18 03:29:54,952 [ search_worker_2][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-18 03:29:55,226 [ search_worker_3][        search][    INFO] Search step 4 beginning (queue size is 33)
2016-08-18 03:29:55,227 [ search_worker_3][      auth_ptc][    INFO] PTC User Login for: 
2016-08-18 03:29:55,817 [ search_worker_3][      auth_ptc][    INFO] PTC User Login successful.
2016-08-18 03:29:55,817 [ search_worker_3][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-18 03:29:55,959 [ search_worker_3][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-18 03:29:56,228 [ search_worker_4][        search][    INFO] Search step 5 beginning (queue size is 32)
2016-08-18 03:29:56,228 [ search_worker_4][      auth_ptc][    INFO] PTC User Login for: 
2016-08-18 03:29:56,808 [ search_worker_4][      auth_ptc][    INFO] PTC User Login successful.
2016-08-18 03:29:56,808 [ search_worker_4][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-18 03:29:56,948 [ search_worker_4][      auth_ptc][    INFO] PTC Access Token successfully retrieved

**Comment by Viper2k4** [comment]
Mh got the same "funny" think. Running 10 Accounts. Got 2 Accounts with this message. Remove the two and got the message for an other account, that was running fine before.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
