### ISSUE TITLE
[   ERROR] Search step 1 map parsing failed, retrying request in 40 seconds

### ISSUE THREAD

**Issue by talentedmrripley** [PokemonGoMap/PokemonGo-Map#816]
When I attempt to run a beehive search I'm getting a lot of error message like this:

2016-08-18 14:11:24,136 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 40 seconds. Username: *****
Traceback (most recent call last):
  File "/home/ripley/PokemonGo-Map/pogom/search.py", line 356, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/ripley/PokemonGo-Map/pogom/models.py", line 382, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-18 14:11:24,848 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 40 seconds. Username: *****
Traceback (most recent call last):
  File "/home/ripley/PokemonGo-Map/pogom/search.py", line 356, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/ripley/PokemonGo-Map/pogom/models.py", line 382, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-18 14:11:25,217 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 40 seconds. Username: *****
Traceback (most recent call last):
  File "/home/ripley/PokemonGo-Map/pogom/search.py", line 356, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/ripley/PokemonGo-Map/pogom/models.py", line 382, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-18 14:11:25,730 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 40 seconds. Username: *****
Traceback (most recent call last):
  File "/home/ripley/PokemonGo-Map/pogom/search.py", line 356, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/ripley/PokemonGo-Map/pogom/models.py", line 382, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-18 14:11:25,941 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 30 seconds. Username: *****
Traceback (most recent call last):
  File "/home/ripley/PokemonGo-Map/pogom/search.py", line 356, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/ripley/PokemonGo-Map/pogom/models.py", line 382, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

## Expected Behavior

Normal output and Pokemon being found.

## Current Behavior

Many errors as above and almost nothing being found

## Steps to Reproduce (for bugs)

1. Clone repo
2. pip install -r requirements.txt
3. npm install and npm run build 
4. Launch search

## Your Environment

* Version used: Cloned about 20 minutes ago
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Ubuntu 16.04.1 LTS

**Comment by blackhattristar** [comment]
Your account may have been banned.

**Comment by SethG911** [comment]
Yep, this means your account is banned. Please check your email for a letter from Niantic. They have implemented new systems that are making scanning near impossible for long.

**Comment by chawenzi** [comment]
same here, and my acc is not banned - can login with it no prob..

**Comment by chawenzi** [comment]
same problem here, acc not banned - can login

**Comment by Climbgunks** [comment]
seeing the same issue..... created ptc account, created and enabled google api keys, cloned repo, built on ubuntu 14.04 LTS.  

printing out the map_dict (credentials removed) -- I'm seeing:
'responses': {'GET_MAP_OBJECTS': {}}, 'status_code': 3, 'unknown6': [{'response_type': 6}],

**Comment by talentedmrripley** [comment]
I just successfully logged in to PTC with an account.  I then tried to run a single search using that account, same error message.

2016-08-18 15:56:27,958 [      MainThread][     runserver][    INFO] Parsed location is: **.****/***.**** (lat/lng/alt)
2016-08-18 15:56:27,961 [      MainThread][        models][    INFO] Connecting to MySQL database on localhost:3306
2016-08-18 15:56:27,965 [   search_thread][        search][    INFO] Search overseer starting
2016-08-18 15:56:27,966 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-18 15:56:27,967 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-18 15:56:27,967 [   search_thread][        search][    INFO] Scan Distance is 0.07 km
2016-08-18 15:56:27,968 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 3)
2016-08-18 15:56:27,968 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: *****
2016-08-18 15:56:28,631 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-18 15:56:28,631 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-18 15:56:28,775 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-18 15:56:29,336 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds. Username: *****

Traceback (most recent call last):
  File "/home/ripley/PokemonGo-Map/pogom/search.py", line 356, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/ripley/PokemonGo-Map/pogom/models.py", line 382, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-18 15:56:39,395 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 20 seconds

**Comment by Climbgunks** [comment]
resolved...by accepting terms of service w/ script found here:
   https://raw.githubusercontent.com/scottstamp/pgoapi/master/scripts/accept-tos.py

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by tgeorge91** [comment]
(I know this is closed, and I hope this doesn't reopen it) - but - I fixed this error by logging into the account on my phone and running through the tutorial.
