### ISSUE TITLE
Newest git clone doesn't work with proxy or config file

### ISSUE THREAD

**Issue by shiznewski** [PokemonGoMap/PokemonGo-Map#850]
I literally just did the git clone 15 minutes ago. The only line i have uncommented in config is proxy (which works fine in my other 3 copies from a week ago).

If i run with the config.ini i get this. Any ideas?  If i try using the command line to set proxy i get a different error.
usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-ld LOGIN_DELAY] [-lr LOGIN_RETRIES] [-sr SCAN_RETRIES]
                    [-dc] [-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m MOCK]
                    [-ns] [-os] [-nsc] [-fl] -k GMAPS_KEY [--spawnpoints-only]
                    [-C] [-D DB] [-cd] [-np] [-ng] [-nk]
                    [-ss [SPAWNPOINT_SCANNING]] [--dump-spawnpoints]
                    [-pd PURGE_DATA] [-px PROXY] [--db-type DB_TYPE]
                    [--db-name DB_NAME] [--db-user DB_USER]
                    [--db-pass DB_PASS] [--db-host DB_HOST]
                    [--db-port DB_PORT]
                    [--db-max_connections DB_MAX_CONNECTIONS]
                    [--db-threads DB_THREADS] [-wh [WEBHOOKS [WEBHOOKS ...]]]
                    [--webhook-updates-only] [--wh-threads WH_THREADS]
                    [--ssl-certificate SSL_CERTIFICATE]
                    [--ssl-privatekey SSL_PRIVATEKEY] [-ps]
runserver.py: error: Unexpected line 0 in /_p/stn/pogom/../config/config.ini: #auth-service:          # ptc (default) or google

Error when setting proxy on command line
2016-08-19 12:42:35,883 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-19 12:42:35,888 [      db-cleaner][        models][    INFO] Regular database cleaning complete
2016-08-19 12:42:35,896 [ search-overseer][        search][    INFO] Search overseer starting
2016-08-19 12:42:35,896 [ search-overseer][        search][    INFO] Starting search worker threads
2016-08-19 12:42:35,897 [ search-overseer][        search][    INFO] New location caught, moving search grid
2016-08-19 12:42:35,897 [ search-overseer][        search][    INFO] Scan Distance is 0.07 km
2016-08-19 12:42:35,980 [ search-worker-0][        search][    INFO] Search step 1 beginning (queue size is 270)
2016-08-19 12:42:35,981 [ search-worker-0][        search][   ERROR] Exception in search_worker: set_authentication() got an unexpected keyword argument 'proxy_config'. Username: #######@gmail.com
Traceback (most recent call last):
  File "/_p/stn/pogom/search.py", line 452, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/_p/stn/pogom/search.py", line 600, in check_login
    api.set_authentication(provider=account['auth_service'], username=account['username'], password=account['password'], proxy_config={'http': args.proxy, 'https': args.proxy})
TypeError: set_authentication() got an unexpected keyword argument 'proxy_config'

**Comment by JapuDCret** [comment]
are you on windows and the editor may have remove the newline-characters? check the config.ini file if every parameter is on a different line

**Comment by teknicsrx7** [comment]
you saved in notepad most likely

**Comment by brandonshults** [comment]
I think you probably just need to upgrade your dependencies.  Try a pip install -r --upgrade requirements.txt

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
