### ISSUE TITLE
Exception in search_worker: can't start new thread

### ISSUE THREAD

**Issue by brettgus** [PokemonGoMap/PokemonGo-Map#852]
## Expected Behavior
Not get errors 

## Current Behavior
When running a spawnscan search with a beehive... when I have enough workers running, i start to get these errors:
2016-08-19 12:13:54,999 [ss_search_worker_0][        search][   ERROR] Exception in search_worker: can't start new thread
Traceback (most recent call last):
  File "/home/user/PokemonGo-Map/pogom/search.py", line 528, in search_worker_thread_ss
    parse_map(response_dict, step_location)
  File "/home/user/PokemonGo-Map/pogom/models.py", line 472, in parse_map
    send_to_webhook('pokestop', webhook_data)
  File "/home/user/PokemonGo-Map/pogom/utils.py", line 330, in send_to_webhook
    wh_thread.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())

## Steps to Reproduce (for bugs)
Run more than 90 workers in -ss mode

## Your Environment

* Version used: Current dev branch
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by justsomedudeonthenet** [comment]
This is likely a problem with your hosting environment.  Perhaps you have a limit on the number of processes you can run on that machine?

What is the output of `ulimit -u`?

**Comment by brettgus** [comment]
Welp, I should have checked my hosting environment first.... looks like my host server can't handle this many workers.
![image](https://cloud.githubusercontent.com/assets/4873772/17818722/57f2e0f4-660a-11e6-9515-834f93976538.png)
TIL -ss definitely hits the server harder than without -ss
