### ISSUE TITLE
Exception on search_worker

### ISSUE THREAD

**Issue by Cronick** [PokemonGoMap/PokemonGo-Map#922]
## Expected Behavior

It should start up the workers but somehow I don't know why i'm getting this error. I have tried to download the latest develop version, but still getting this error.
## Current Behavior

`2016-08-22 12:38:01,366 [     ss-worker-5][        search][   ERROR] Exception in search_worker:
Traceback (most recent call last):
  File "/root/go-test2/pogom/search.py", line 566, in search_worker_thread_ss
    api.set_proxy({'http': args.proxy, 'https': args.proxy})
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 126, in __getattr__
    raise AttributeError
AttributeError
Exception in thread ss-worker-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/go-test2/pogom/search.py", line 634, in search_worker_thread_ss
    time.sleep(sleep_time)
UnboundLocalError: local variable 'sleep_time' referenced before assignment
`
## Context

The workers are not starting up

## Your Environment

* Version used: Latest develop version
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Debian 8

**Comment by isgajor** [comment]
I got a similar error.
2016-08-22 12:58:21,536 [ search_worker_0][        search][   ERROR] Exception in search_worker: perform_master_login() got an unexpected keyword argument 'proxy'. Username: <username>

**Comment by justsomedudeonthenet** [comment]
Exactly which commit are you running?

**Comment by Cronick** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/tree/16b92950ac48e3bf3a310e6807765cea70267175

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
