### ISSUE TITLE
Not working with Google accounts? (not a support request)

### ISSUE THREAD

**Issue by Dcstegg228** [PokemonGoMap/PokemonGo-Map#926]
## Expected Behavior

The map should run normally. (And it does with a PTC account)

## Current Behavior
I have a confirmed working(Logged in on a phone and it works) Google account.
When I run the map I get this error

2016-08-22 07:57:16,392 [ search-overseer][        search][    INFO] Search overseer starting
2016-08-22 07:57:16,394 [ search-overseer][        search][    INFO] Starting search worker threads
2016-08-22 07:57:16,394 [      db-cleaner][        models][    INFO] Regular database cleaning complete
2016-08-22 07:57:16,397 [ search-overseer][        search][    INFO] New location caught, moving search grid
2016-08-22 07:57:16,401 [ search-overseer][        search][    INFO] Scan Distance is 0.07 km
2016-08-22 07:57:16,418 [ search-worker-0][        search][    INFO] Search step 1 beginning (queue size is 2)
2016-08-22 07:57:16,420 [ search-worker-0][   auth_google][    INFO] Google User Login for: acadia1005@gmail.com
2016-08-22 07:57:16,421 [ search-worker-0][        search][   ERROR] Exception in search_worker: perform_master_login() got an unexpected keyword argument 'proxy'. Username: acadia1005@gmail.com
Traceback (most recent call last):
  File "C:\PokemonGo-Map\pogom\search.py", line 504, in search_worker_thread
    check_login(args, account, api, step_location)
  File "C:\PokemonGo-Map\pogom\search.py", line 654, in check_login
    api.set_authentication(provider=account['auth_service'], username=account['username'], password=account['password'])
  File "C:\Users\lib\site-packages\pgoapi\pgoapi.py", line 92, in set_authentication
    self._auth_provider.user_login(username, password)
  File "C:\Users\lib\site-packages\pgoapi\auth_google.py", line 58, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID, proxy=self._proxy)
TypeError: perform_master_login() got an unexpected keyword argument 'proxy'

## Steps to Reproduce (for bugs)
1.Run from git bash or command line
2.python runserver.py -a google -u googleaccount@gmail.com -p password -l "43.054868 -78.899176" -st 10 -k GmapsKey

## Context
Everything is working with PTC but not Google.
I have been using this map for weeks and then I updated today and now this is happening.

## Your Environment

* Version used: latest dev as of right now.
* python 2.7
* Windows 10

**Comment by Isgajor** [comment]
I got exactly the same thing! Everything is working with a PTC.

**Comment by Braini01** [comment]
It seems gpsoauth version 0.4.0 instead of 0.3.0 is needed now, so requirements.txt needs to be updated

**Comment by tkSimon** [comment]
updating to 0.4.0 solved the issue for me
