### ISSUE TITLE
Closing browser while requesting data breaks socket-pipe

### ISSUE THREAD

**Issue by ilendemli** [PokemonGoMap/PokemonGo-Map#929]
## Expected Behavior
Maybe print a message or even skip/ignore it

## Current Behavior
Shows that the socket-pipe in thread crashes:

```
Exception in thread Thread-64:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

## Steps to Reproduce (for bugs)

1. Start server
2. Check console for data to be requested
3. Close the window or abort the request
4. Check terminal

## Your Environment
* Version used: develop branch where latest commit has following hash: 16b9295 
* Environment name and version (e.g. Python 2.7): Raspberry Pi Zero Python 2.7.9
* Operating System and version (desktop or mobile): Jessy Debian

**Comment by BaIthamel** [comment]
Known issue, is in discussion elsewhere.
