### ISSUE TITLE
Account name not printed after a failed account

### ISSUE THREAD

**Issue by aldarund** [PokemonGoMap/PokemonGo-Map#936]
After  #935 name of failed account stopped to appear in logs so impossible to say what account fails.
All that in logs doesnt help to find banned worker
```
2016-08-22 18:16:35,565 [ search-worker-0][        search][    INFO] Searching at 52.403761,30.980693
2016-08-22 18:16:35,676 [ search-worker-0][        search][   ERROR] Map parse failed at 52.403761,30.980693, abandoning location
Traceback (most recent call last):
  File "/opt/webapps/pogomap/PokemonGo-Map/pogom/search.py", line 504, in search_worker_thread
    findCount = parse_map(args, response_dict, step_location, dbq, whq)
  File "/opt/webapps/pogomap/PokemonGo-Map/pogom/models.py", line 387, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
```

**Comment by lota7** [comment]
Right now you can look at worker-0 indicating it being the first account in your commandline

**Comment by aldarund** [comment]
i dont see how worker-0 better than the actual account name.

**Comment by aldarund** [comment]
fixed in https://github.com/PokemonGoMap/PokemonGo-Map/pull/941
