### ISSUE TITLE
Error after starting

### ISSUE THREAD

**Issue by patgi** [PokemonGoMap/PokemonGo-Map#97]
I got an error when i start the script:

TypeError: sequence index must be integer, not 'str'
2016-08-08 11:13:42,148 [ search_worker_0][        search][    INFO] Search step 38 beginning (queue size is 359)
2016-08-08 11:13:42,148 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: p****
2016-08-08 11:13:42,470 [ search_worker_0][      auth_ptc][   ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-08 11:13:42,479 [ search_worker_0][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/data/www/default/test2/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/data/www/default/test2/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'
2016-08-08 11:13:42,481 [ search_worker_0][        search][    INFO] Search step 39 beginning (queue size is 358)
2016-08-08 11:13:42,481 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: p****
2016-08-08 11:13:42,804 [ search_worker_0][      auth_ptc][   ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-08 11:13:42,813 [ search_worker_0][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/data/www/default/test2/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/data/www/default/test2/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'
2016-08-08 11:13:42,815 [ search_worker_0][        search][    INFO] Search step 40 beginning (queue size is 357)
2016-08-08 11:13:42,815 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: p****
2016-08-08 11:13:43,142 [ search_worker_0][      auth_ptc][   ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-08 11:13:43,151 [ search_worker_0][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/data/www/default/test2/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/data/www/default/test2/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'
...
...
...

**Comment by LIJE** [comment]
PTC Account is not active. Banned? Not confirmed?

**Comment by patgi** [comment]
Looks like it, I made a new account.
I got now a token back, but with the same errors.

2016-08-08 11:21:28,105 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-08 11:21:28,105 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-08 11:21:28,242 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-08 11:21:28,798 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds
Traceback (most recent call last):
  File "/data/www/default/test2/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/data/www/default/test2/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-08 11:21:39,103 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 20 seconds
Traceback (most recent call last):
  File "/data/www/default/test2/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/data/www/default/test2/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-08 11:21:59,623 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 30 seconds
Traceback (most recent call last):
  File "/data/www/default/test2/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/data/www/default/test2/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by freakjam** [comment]
Did u set the Google Maps API key in your config file?

**Comment by patgi** [comment]
Its working after I complete the tutorial (i used bluestark to do this)...
