### ISSUE TITLE
receiving this error when trying to run the programme never had a problem with any of the others

### ISSUE THREAD

**Issue by TWIISTED-SHOPS** [PokemonGoMap/PokemonGo-Map#978]
2016-08-25 00:29:45,904 [      MainThread][     runserver][    INFO] Parsed location is: 53.7925/-1.7547/108.5368 (lat/lng/alt)
2016-08-25 00:29:45,914 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-25 00:29:45,921 [   search_thread][        search][    INFO] Search overseer starting
2016-08-25 00:29:45,926 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-25 00:29:45,931 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-25 00:29:45,940 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 0)
2016-08-25 00:29:45,944 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: buggerlugs01
2016-08-25 00:29:46,598 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-25 00:29:46,599 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-25 00:29:46,743 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-25 00:29:47,697 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds. Username: buggerlugs01
Traceback (most recent call last):
  File "C:\Users\Antony\Desktop\PokemonGo-Map-3.1.0\PokemonGo-Map-3.1.0\pogom\search.py", line 254, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Users\Antony\Desktop\PokemonGo-Map-3.1.0\PokemonGo-Map-3.1.0\pogom\models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by swtrpeter** [comment]
Having this issue as well.

**Comment by nhumber** [comment]
i had to open the game and re accept the TOS, is it possible that with pokemon .35 any new, previously activated accounts now need the TOS accepted again?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by averylarry** [comment]
That's what banned accounts look like currently.
